# Generated by Django 5.2.10 on 2026-02-01 05:29

import app.utils
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('code_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('get_short_name', models.TextField(default='user', max_length=250)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_confirm', models.BooleanField(default=False)),
                ('in_newsletter', models.BooleanField(default=False)),
                ('uuid', models.CharField(default=app.utils.Utils.generate_uuid, max_length=250)),
                ('confirmation_token', models.CharField(default=app.utils.Utils.generate_hex_uuid, max_length=250, null=True)),
                ('verification_code', models.CharField(blank=True, default=app.utils.Utils.genetate_verification_code, max_length=10, null=True)),
                ('verification_code_sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('restore_password_token', models.CharField(max_length=250, null=True)),
                ('lost_password_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('lang', models.CharField(default='en', max_length=5)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('api_token', models.CharField(blank=True, default=app.utils.Utils.generate_hex_uuid, max_length=250, null=True)),
                ('card_nonce', models.CharField(blank=True, max_length=250, null=True)),
                ('payment_nonce', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('processor', models.CharField(blank=True, max_length=50, null=True)),
                ('credits', models.IntegerField(blank=True, default=0)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('plan_subscribed', models.CharField(blank=True, max_length=50, null=True)),
                ('is_plan_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('uuid', models.CharField(default=app.utils.Utils.generate_hex_uuid, max_length=250)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
