# Generated by Django 5.2.10 on 2026-02-05 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_url', models.URLField(blank=True, help_text='URL to custom logo')),
                ('favicon_url', models.URLField(blank=True, help_text='URL to custom favicon')),
                ('background_url', models.URLField(blank=True, help_text='URL to custom background image')),
                ('primary_color', models.CharField(default='#111111', help_text='Primary brand color (hex)', max_length=7)),
                ('secondary_color', models.CharField(default='#f5f5f5', help_text='Secondary color (hex)', max_length=7)),
                ('text_color', models.CharField(default='#111111', help_text='Text color (hex)', max_length=7)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('hide_sendfiles_branding', models.BooleanField(default=False, help_text="Hide 'Powered by SendFiles' text")),
                ('custom_footer_text', models.TextField(blank=True)),
                ('custom_domain', models.CharField(blank=True, help_text='Custom domain for transfers', max_length=255)),
                ('custom_domain_verified', models.BooleanField(default=False)),
                ('email_logo_url', models.URLField(blank=True)),
                ('email_footer_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Branding',
                'verbose_name_plural': 'User Brandings',
            },
        ),
    ]
