"""
Platform configuration for dynamic "Send Large Files on {Platform}" pages.
This enables long-tail SEO targeting searches like "how to send large files on whatsapp".
"""

PLATFORM_CATEGORIES = {
    'messaging': {
        'name': 'Messaging Apps',
        'description': 'Popular messaging and chat applications',
        'order': 1,
    },
    'social': {
        'name': 'Social Media',
        'description': 'Social networking platforms',
        'order': 2,
    },
    'email': {
        'name': 'Email Services',
        'description': 'Email providers and clients',
        'order': 3,
    },
    'professional': {
        'name': 'Professional & Business',
        'description': 'Workplace collaboration tools',
        'order': 4,
    },
    'dating': {
        'name': 'Dating Apps',
        'description': 'Dating and social connection apps',
        'order': 5,
    },
    'gaming': {
        'name': 'Gaming Platforms',
        'description': 'Gaming and streaming platforms',
        'order': 6,
    },
    'cloud': {
        'name': 'Cloud Storage',
        'description': 'Cloud storage and file hosting services',
        'order': 7,
    },
}

PLATFORMS = {
    # ==================== MESSAGING APPS ====================
    'whatsapp': {
        'name': 'WhatsApp',
        'slug': 'whatsapp',
        'icon': 'whatsapp',
        'color': '#25D366',
        'category': 'messaging',
        'file_limit': '2GB',
        'file_limit_note': '2GB per file, but quality is compressed',
        'users': '2 billion',
        'share_method': 'chat message',
        'share_instruction': 'Open any chat conversation, tap the message field, paste your SendFiles.Online link, and tap send. Your recipient can tap the link to download instantly.',
        'app_instruction': 'Open WhatsApp on your phone or WhatsApp Web on your computer',
        'is_active': True,
    },
    'facebook-messenger': {
        'name': 'Facebook Messenger',
        'slug': 'facebook-messenger',
        'icon': 'facebook-messenger',
        'color': '#0084FF',
        'category': 'messaging',
        'file_limit': '25MB',
        'file_limit_note': '25MB for most file types',
        'users': '1 billion',
        'share_method': 'message',
        'share_instruction': 'Open a Messenger conversation, paste your SendFiles.Online link in the message box, and hit send. The link will appear as a clickable preview.',
        'app_instruction': 'Open Messenger app or messenger.com in your browser',
        'is_active': True,
    },
    'telegram': {
        'name': 'Telegram',
        'slug': 'telegram',
        'icon': 'telegram',
        'color': '#0088CC',
        'category': 'messaging',
        'file_limit': '2GB',
        'file_limit_note': '2GB per file with Telegram Premium, 1.5GB for free users',
        'users': '800 million',
        'share_method': 'message',
        'share_instruction': 'Open any Telegram chat, paste your SendFiles.Online link, and send. Telegram will show a rich link preview automatically.',
        'app_instruction': 'Open Telegram on any device - mobile, desktop, or web',
        'is_active': True,
    },
    'signal': {
        'name': 'Signal',
        'slug': 'signal',
        'icon': 'signal',
        'color': '#3A76F0',
        'category': 'messaging',
        'file_limit': '100MB',
        'file_limit_note': '100MB per attachment',
        'users': '40 million',
        'share_method': 'message',
        'share_instruction': 'Open a Signal conversation, paste your SendFiles.Online link, and send. Your contact will receive a secure, clickable link.',
        'app_instruction': 'Open Signal on your phone or Signal Desktop',
        'is_active': True,
    },
    'imessage': {
        'name': 'iMessage',
        'slug': 'imessage',
        'icon': 'apple',
        'color': '#34C759',
        'category': 'messaging',
        'file_limit': '100MB',
        'file_limit_note': '100MB, larger files sent via iCloud link',
        'users': '1.3 billion',
        'share_method': 'text message',
        'share_instruction': 'Open Messages on your iPhone, iPad, or Mac. Start a conversation, paste your SendFiles.Online link, and send. Works for both iMessage and SMS recipients.',
        'app_instruction': 'Open the Messages app on any Apple device',
        'is_active': True,
    },
    'discord': {
        'name': 'Discord',
        'slug': 'discord',
        'icon': 'discord',
        'color': '#5865F2',
        'category': 'messaging',
        'file_limit': '25MB',
        'file_limit_note': '25MB free, 500MB with Nitro',
        'users': '200 million',
        'share_method': 'message',
        'share_instruction': 'Open any Discord channel or DM, paste your SendFiles.Online link, and send. Discord will embed a preview of your transfer.',
        'app_instruction': 'Open Discord app or discord.com',
        'is_active': True,
    },
    'slack': {
        'name': 'Slack',
        'slug': 'slack',
        'icon': 'slack',
        'color': '#4A154B',
        'category': 'messaging',
        'file_limit': '1GB',
        'file_limit_note': '1GB per file on paid plans, limited storage on free',
        'users': '32 million',
        'share_method': 'message',
        'share_instruction': 'Open any Slack channel or direct message, paste your SendFiles.Online link, and send. Slack will unfurl the link with a preview.',
        'app_instruction': 'Open Slack on desktop, mobile, or web',
        'is_active': True,
    },
    'microsoft-teams': {
        'name': 'Microsoft Teams',
        'slug': 'microsoft-teams',
        'icon': 'microsoft',
        'color': '#6264A7',
        'category': 'messaging',
        'file_limit': '250GB',
        'file_limit_note': '250GB per file, but requires Office 365',
        'users': '320 million',
        'share_method': 'message',
        'share_instruction': 'Open a Teams chat or channel, paste your SendFiles.Online link in the message box, and send. Anyone in the conversation can click to download.',
        'app_instruction': 'Open Microsoft Teams app or teams.microsoft.com',
        'is_active': True,
    },
    'wechat': {
        'name': 'WeChat',
        'slug': 'wechat',
        'icon': 'weixin',
        'color': '#07C160',
        'category': 'messaging',
        'file_limit': '100MB',
        'file_limit_note': '100MB for files, 25MB for videos',
        'users': '1.3 billion',
        'share_method': 'message',
        'share_instruction': 'Open a WeChat conversation, paste your SendFiles.Online link, and send. Your contact can tap the link to download the files.',
        'app_instruction': 'Open WeChat on your mobile device',
        'is_active': True,
    },
    'line': {
        'name': 'LINE',
        'slug': 'line',
        'icon': 'line',
        'color': '#00B900',
        'category': 'messaging',
        'file_limit': '300MB',
        'file_limit_note': '300MB per file',
        'users': '178 million',
        'share_method': 'message',
        'share_instruction': 'Open a LINE chat, paste your SendFiles.Online link, and send. LINE will display a link preview for easy access.',
        'app_instruction': 'Open LINE app on mobile or desktop',
        'is_active': True,
    },
    'viber': {
        'name': 'Viber',
        'slug': 'viber',
        'icon': 'viber',
        'color': '#7360F2',
        'category': 'messaging',
        'file_limit': '200MB',
        'file_limit_note': '200MB per file',
        'users': '260 million',
        'share_method': 'message',
        'share_instruction': 'Open a Viber chat, paste your SendFiles.Online link, and send. Your recipient will see a tappable link to download.',
        'app_instruction': 'Open Viber on mobile or desktop',
        'is_active': True,
    },
    'snapchat': {
        'name': 'Snapchat',
        'slug': 'snapchat',
        'icon': 'snapchat',
        'color': '#FFFC00',
        'text_color': '#000000',
        'category': 'messaging',
        'file_limit': '2.5MB',
        'file_limit_note': '2.5MB for snaps, 64MB for memories',
        'users': '800 million',
        'share_method': 'chat',
        'share_instruction': 'Open a Snapchat chat conversation, paste your SendFiles.Online link, and send. Your friend can tap the link to view and download files.',
        'app_instruction': 'Open Snapchat and go to the Chat section',
        'is_active': True,
    },
    'skype': {
        'name': 'Skype',
        'slug': 'skype',
        'icon': 'skype',
        'color': '#00AFF0',
        'category': 'messaging',
        'file_limit': '300MB',
        'file_limit_note': '300MB per file',
        'users': '300 million',
        'share_method': 'message',
        'share_instruction': 'Open a Skype conversation, paste your SendFiles.Online link in the chat, and send. The link will be clickable for all participants.',
        'app_instruction': 'Open Skype on desktop, mobile, or web',
        'is_active': True,
    },

    # ==================== SOCIAL MEDIA ====================
    'instagram': {
        'name': 'Instagram',
        'slug': 'instagram',
        'icon': 'instagram',
        'color': '#E4405F',
        'category': 'social',
        'file_limit': '650MB',
        'file_limit_note': '650MB for Reels, no file sharing in DMs',
        'users': '2 billion',
        'share_method': 'direct message',
        'share_instruction': 'Open Instagram DMs, start or open a conversation, paste your SendFiles.Online link, and send. Instagram will show a tappable link for your recipient.',
        'app_instruction': 'Open Instagram app and tap the messenger icon',
        'is_active': True,
    },
    'facebook': {
        'name': 'Facebook',
        'slug': 'facebook',
        'icon': 'facebook',
        'color': '#1877F2',
        'category': 'social',
        'file_limit': '25MB',
        'file_limit_note': '25MB for attachments in posts and messages',
        'users': '3 billion',
        'share_method': 'post or message',
        'share_instruction': 'Share your SendFiles.Online link in a Facebook post, comment, or send it via Messenger. Facebook will display a rich preview with your transfer details.',
        'app_instruction': 'Open Facebook app or facebook.com',
        'is_active': True,
    },
    'twitter': {
        'name': 'X (Twitter)',
        'slug': 'twitter',
        'icon': 'x-twitter',
        'color': '#000000',
        'category': 'social',
        'file_limit': '15MB',
        'file_limit_note': '15MB for images, 512MB for video with Premium',
        'users': '600 million',
        'share_method': 'tweet or DM',
        'share_instruction': 'Tweet your SendFiles.Online link or send it in a direct message. X will display a link card preview so your followers know what to expect.',
        'app_instruction': 'Open X (Twitter) app or x.com',
        'is_active': True,
    },
    'tiktok': {
        'name': 'TikTok',
        'slug': 'tiktok',
        'icon': 'tiktok',
        'color': '#000000',
        'category': 'social',
        'file_limit': '287MB',
        'file_limit_note': '287MB for videos, no file sharing feature',
        'users': '1.5 billion',
        'share_method': 'direct message or bio',
        'share_instruction': 'Send your SendFiles.Online link via TikTok DM, or add it to your bio for your followers. Recipients can tap the link to download your files.',
        'app_instruction': 'Open TikTok app and go to messages or your profile',
        'is_active': True,
    },
    'linkedin': {
        'name': 'LinkedIn',
        'slug': 'linkedin',
        'icon': 'linkedin',
        'color': '#0A66C2',
        'category': 'social',
        'file_limit': '100MB',
        'file_limit_note': '100MB for documents, 5GB for videos',
        'users': '1 billion',
        'share_method': 'post or message',
        'share_instruction': 'Share your SendFiles.Online link in a LinkedIn post or send it via LinkedIn messaging. Perfect for sharing large presentations, portfolios, or work files professionally.',
        'app_instruction': 'Open LinkedIn app or linkedin.com',
        'is_active': True,
    },
    'reddit': {
        'name': 'Reddit',
        'slug': 'reddit',
        'icon': 'reddit',
        'color': '#FF4500',
        'category': 'social',
        'file_limit': '20MB',
        'file_limit_note': '20MB for images, 1GB for videos',
        'users': '1.7 billion',
        'share_method': 'post or comment',
        'share_instruction': 'Share your SendFiles.Online link in a Reddit post, comment, or direct message. Other Redditors can click through to download your shared files.',
        'app_instruction': 'Open Reddit app or reddit.com',
        'is_active': True,
    },
    'pinterest': {
        'name': 'Pinterest',
        'slug': 'pinterest',
        'icon': 'pinterest',
        'color': '#E60023',
        'category': 'social',
        'file_limit': '20MB',
        'file_limit_note': '20MB for images',
        'users': '480 million',
        'share_method': 'message',
        'share_instruction': 'Send your SendFiles.Online link via Pinterest messages or add it to a pin description. Great for sharing high-resolution design files or project assets.',
        'app_instruction': 'Open Pinterest app or pinterest.com',
        'is_active': True,
    },
    'threads': {
        'name': 'Threads',
        'slug': 'threads',
        'icon': 'threads',
        'color': '#000000',
        'category': 'social',
        'file_limit': '10MB',
        'file_limit_note': 'Limited file support, image-focused',
        'users': '200 million',
        'share_method': 'post',
        'share_instruction': 'Post your SendFiles.Online link on Threads. Your followers can tap the link to access and download your shared files.',
        'app_instruction': 'Open Threads app',
        'is_active': True,
    },
    'tumblr': {
        'name': 'Tumblr',
        'slug': 'tumblr',
        'icon': 'tumblr',
        'color': '#36465D',
        'category': 'social',
        'file_limit': '100MB',
        'file_limit_note': '100MB for videos, 20MB for images',
        'users': '135 million',
        'share_method': 'post',
        'share_instruction': 'Create a Tumblr post with your SendFiles.Online link. Perfect for sharing large art files, videos, or creative projects with your followers.',
        'app_instruction': 'Open Tumblr app or tumblr.com',
        'is_active': True,
    },

    # ==================== EMAIL SERVICES ====================
    'gmail': {
        'name': 'Gmail',
        'slug': 'gmail',
        'icon': 'google',
        'color': '#EA4335',
        'category': 'email',
        'file_limit': '25MB',
        'file_limit_note': '25MB total per email including all attachments',
        'users': '1.8 billion',
        'share_method': 'email',
        'share_instruction': 'Compose a new email in Gmail, paste your SendFiles.Online link in the body, and send. Much easier than dealing with attachment limits or Google Drive sharing settings.',
        'app_instruction': 'Open Gmail app or gmail.com',
        'is_active': True,
    },
    'outlook': {
        'name': 'Outlook',
        'slug': 'outlook',
        'icon': 'microsoft',
        'color': '#0078D4',
        'category': 'email',
        'file_limit': '20MB',
        'file_limit_note': '20MB for Outlook.com, varies for Office 365',
        'users': '400 million',
        'share_method': 'email',
        'share_instruction': 'Compose an email in Outlook, paste your SendFiles.Online link, and send. Avoid attachment limits and ensure your recipient can access files regardless of their email provider.',
        'app_instruction': 'Open Outlook app or outlook.com',
        'is_active': True,
    },
    'yahoo-mail': {
        'name': 'Yahoo Mail',
        'slug': 'yahoo-mail',
        'icon': 'yahoo',
        'color': '#6001D2',
        'category': 'email',
        'file_limit': '25MB',
        'file_limit_note': '25MB total per email',
        'users': '225 million',
        'share_method': 'email',
        'share_instruction': 'Compose an email in Yahoo Mail, paste your SendFiles.Online link, and send. Your recipient can download files with a single click.',
        'app_instruction': 'Open Yahoo Mail app or mail.yahoo.com',
        'is_active': True,
    },
    'protonmail': {
        'name': 'ProtonMail',
        'slug': 'protonmail',
        'icon': 'envelope',
        'color': '#6D4AFF',
        'category': 'email',
        'file_limit': '25MB',
        'file_limit_note': '25MB on free plan',
        'users': '100 million',
        'share_method': 'email',
        'share_instruction': 'Compose a secure email in ProtonMail, paste your SendFiles.Online link, and send. Combine ProtonMail\'s encryption with our secure file transfers.',
        'app_instruction': 'Open ProtonMail app or mail.proton.me',
        'is_active': True,
    },
    'apple-mail': {
        'name': 'Apple Mail',
        'slug': 'apple-mail',
        'icon': 'apple',
        'color': '#007AFF',
        'category': 'email',
        'file_limit': '20MB',
        'file_limit_note': '20MB default, Mail Drop for larger files up to 5GB',
        'users': '500 million',
        'share_method': 'email',
        'share_instruction': 'Compose an email in Apple Mail, paste your SendFiles.Online link, and send. Works seamlessly on iPhone, iPad, and Mac.',
        'app_instruction': 'Open Mail app on any Apple device',
        'is_active': True,
    },
    'zoho-mail': {
        'name': 'Zoho Mail',
        'slug': 'zoho-mail',
        'icon': 'envelope',
        'color': '#C8202B',
        'category': 'email',
        'file_limit': '25MB',
        'file_limit_note': '25MB per email',
        'users': '15 million',
        'share_method': 'email',
        'share_instruction': 'Compose an email in Zoho Mail, paste your SendFiles.Online link, and send. Perfect for business file sharing without attachment hassles.',
        'app_instruction': 'Open Zoho Mail app or mail.zoho.com',
        'is_active': True,
    },

    # ==================== PROFESSIONAL & BUSINESS ====================
    'zoom': {
        'name': 'Zoom',
        'slug': 'zoom',
        'icon': 'video',
        'color': '#2D8CFF',
        'category': 'professional',
        'file_limit': '1GB',
        'file_limit_note': '1GB for cloud recordings, 512MB for chat files',
        'users': '300 million',
        'share_method': 'chat or meeting',
        'share_instruction': 'Share your SendFiles.Online link in Zoom chat during a meeting, or paste it in Team Chat. All participants can click to download the files.',
        'app_instruction': 'Open Zoom app and go to chat or start a meeting',
        'is_active': True,
    },
    'google-meet': {
        'name': 'Google Meet',
        'slug': 'google-meet',
        'icon': 'google',
        'color': '#00897B',
        'category': 'professional',
        'file_limit': 'N/A',
        'file_limit_note': 'No direct file sharing in Meet',
        'users': '300 million',
        'share_method': 'chat',
        'share_instruction': 'During a Google Meet call, open the in-meeting chat and paste your SendFiles.Online link. Or share via Google Chat before/after the meeting.',
        'app_instruction': 'Join a Google Meet call and open the chat panel',
        'is_active': True,
    },
    'notion': {
        'name': 'Notion',
        'slug': 'notion',
        'icon': 'n',
        'color': '#000000',
        'category': 'professional',
        'file_limit': '5MB',
        'file_limit_note': '5MB on free plan, unlimited on paid',
        'users': '35 million',
        'share_method': 'page or database',
        'share_instruction': 'Add your SendFiles.Online link to any Notion page, database, or comment. Notion will display it as a bookmark with a preview.',
        'app_instruction': 'Open Notion app or notion.so',
        'is_active': True,
    },
    'trello': {
        'name': 'Trello',
        'slug': 'trello',
        'icon': 'trello',
        'color': '#0052CC',
        'category': 'professional',
        'file_limit': '10MB',
        'file_limit_note': '10MB on free plan, 250MB on paid',
        'users': '50 million',
        'share_method': 'card',
        'share_instruction': 'Add your SendFiles.Online link to a Trello card description, comment, or attachment. Team members can click to download associated files.',
        'app_instruction': 'Open Trello and navigate to your board',
        'is_active': True,
    },
    'asana': {
        'name': 'Asana',
        'slug': 'asana',
        'icon': 'check-circle',
        'color': '#F06A6A',
        'category': 'professional',
        'file_limit': '100MB',
        'file_limit_note': '100MB per attachment',
        'users': '140 million',
        'share_method': 'task or comment',
        'share_instruction': 'Add your SendFiles.Online link to any Asana task description or comment. Perfect for sharing large project files with your team.',
        'app_instruction': 'Open Asana app or app.asana.com',
        'is_active': True,
    },
    'jira': {
        'name': 'Jira',
        'slug': 'jira',
        'icon': 'jira',
        'color': '#0052CC',
        'category': 'professional',
        'file_limit': '10MB',
        'file_limit_note': '10MB per attachment on cloud',
        'users': '10 million',
        'share_method': 'issue or comment',
        'share_instruction': 'Add your SendFiles.Online link to a Jira issue description or comment. Great for sharing large log files, screenshots, or documentation with your development team.',
        'app_instruction': 'Open Jira and navigate to your project',
        'is_active': True,
    },
    'github': {
        'name': 'GitHub',
        'slug': 'github',
        'icon': 'github',
        'color': '#181717',
        'category': 'professional',
        'file_limit': '100MB',
        'file_limit_note': '100MB per file, 50MB for web uploads',
        'users': '100 million',
        'share_method': 'issue, PR, or comment',
        'share_instruction': 'Add your SendFiles.Online link to a GitHub issue, pull request, or comment. Perfect for sharing large binaries, test files, or assets that shouldn\'t be in the repo.',
        'app_instruction': 'Open GitHub and navigate to your repository',
        'is_active': True,
    },
    'confluence': {
        'name': 'Confluence',
        'slug': 'confluence',
        'icon': 'confluence',
        'color': '#172B4D',
        'category': 'professional',
        'file_limit': '10MB',
        'file_limit_note': '10MB per attachment on cloud',
        'users': '75,000 teams',
        'share_method': 'page',
        'share_instruction': 'Embed your SendFiles.Online link in any Confluence page. Confluence will display a smart link card for easy access.',
        'app_instruction': 'Open Confluence and edit a page',
        'is_active': True,
    },
    'monday': {
        'name': 'Monday.com',
        'slug': 'monday',
        'icon': 'calendar-check',
        'color': '#FF3D57',
        'category': 'professional',
        'file_limit': '500MB',
        'file_limit_note': '500MB per file',
        'users': '225,000 teams',
        'share_method': 'item or update',
        'share_instruction': 'Add your SendFiles.Online link to any Monday item or update. Team members can access large files directly from your workflow.',
        'app_instruction': 'Open Monday.com and navigate to your board',
        'is_active': True,
    },
    'basecamp': {
        'name': 'Basecamp',
        'slug': 'basecamp',
        'icon': 'campground',
        'color': '#1D2D35',
        'category': 'professional',
        'file_limit': 'Unlimited',
        'file_limit_note': 'No limit, but can be slow for very large files',
        'users': 'millions',
        'share_method': 'message or docs',
        'share_instruction': 'Share your SendFiles.Online link in Basecamp messages or Docs & Files. Fast and reliable large file sharing for your team.',
        'app_instruction': 'Open Basecamp and navigate to your project',
        'is_active': True,
    },

    # ==================== DATING APPS ====================
    'tinder': {
        'name': 'Tinder',
        'slug': 'tinder',
        'icon': 'fire',
        'color': '#FE3C72',
        'category': 'dating',
        'file_limit': 'N/A',
        'file_limit_note': 'No file sharing, limited to photos',
        'users': '75 million',
        'share_method': 'message',
        'share_instruction': 'Send your SendFiles.Online link in a Tinder chat. Perfect for sharing photos, playlists, or other files with your match safely.',
        'app_instruction': 'Open Tinder and go to your matches',
        'is_active': True,
    },
    'bumble': {
        'name': 'Bumble',
        'slug': 'bumble',
        'icon': 'bee',
        'color': '#FFC629',
        'text_color': '#000000',
        'category': 'dating',
        'file_limit': 'N/A',
        'file_limit_note': 'No file sharing feature',
        'users': '45 million',
        'share_method': 'message',
        'share_instruction': 'Share your SendFiles.Online link in a Bumble conversation. A safe way to share photos or files with new connections.',
        'app_instruction': 'Open Bumble and go to your conversations',
        'is_active': True,
    },
    'hinge': {
        'name': 'Hinge',
        'slug': 'hinge',
        'icon': 'heart',
        'color': '#F24C86',
        'category': 'dating',
        'file_limit': 'N/A',
        'file_limit_note': 'No file sharing feature',
        'users': '23 million',
        'share_method': 'message',
        'share_instruction': 'Send your SendFiles.Online link in a Hinge chat to share photos, videos, or other files with your potential match.',
        'app_instruction': 'Open Hinge and go to your matches',
        'is_active': True,
    },

    # ==================== GAMING PLATFORMS ====================
    'steam': {
        'name': 'Steam',
        'slug': 'steam',
        'icon': 'steam',
        'color': '#171A21',
        'category': 'gaming',
        'file_limit': 'N/A',
        'file_limit_note': 'No file sharing in chat',
        'users': '120 million',
        'share_method': 'chat',
        'share_instruction': 'Send your SendFiles.Online link via Steam Chat to share game mods, screenshots, or other files with your gaming friends.',
        'app_instruction': 'Open Steam and go to Friends & Chat',
        'is_active': True,
    },
    'playstation': {
        'name': 'PlayStation',
        'slug': 'playstation',
        'icon': 'playstation',
        'color': '#003791',
        'category': 'gaming',
        'file_limit': 'N/A',
        'file_limit_note': 'No file sharing feature',
        'users': '108 million',
        'share_method': 'message',
        'share_instruction': 'Send your SendFiles.Online link via PlayStation messages to share game clips, screenshots, or files with your PSN friends.',
        'app_instruction': 'Open PlayStation App or use your console',
        'is_active': True,
    },
    'xbox': {
        'name': 'Xbox',
        'slug': 'xbox',
        'icon': 'xbox',
        'color': '#107C10',
        'category': 'gaming',
        'file_limit': 'N/A',
        'file_limit_note': 'No file sharing feature',
        'users': '120 million',
        'share_method': 'message',
        'share_instruction': 'Send your SendFiles.Online link via Xbox messages to share game clips, screenshots, or files with your Xbox friends.',
        'app_instruction': 'Open Xbox App or use your console',
        'is_active': True,
    },
    'twitch': {
        'name': 'Twitch',
        'slug': 'twitch',
        'icon': 'twitch',
        'color': '#9146FF',
        'category': 'gaming',
        'file_limit': 'N/A',
        'file_limit_note': 'No file sharing in chat',
        'users': '140 million',
        'share_method': 'chat or whisper',
        'share_instruction': 'Share your SendFiles.Online link in Twitch chat or via whisper. Great for sharing stream overlays, assets, or files with your community.',
        'app_instruction': 'Open Twitch app or twitch.tv',
        'is_active': True,
    },

    # ==================== CLOUD STORAGE ====================
    'google-drive': {
        'name': 'Google Drive',
        'slug': 'google-drive',
        'icon': 'google-drive',
        'color': '#4285F4',
        'category': 'cloud',
        'file_limit': '5TB',
        'file_limit_note': '5TB per file, but sharing requires Google account',
        'users': '1 billion',
        'share_method': 'link sharing',
        'share_instruction': 'When Google Drive sharing permissions are too complex, use SendFiles.Online instead. Upload files, get a link, and share without requiring recipients to have Google accounts.',
        'app_instruction': 'Compare with drive.google.com',
        'is_active': True,
    },
    'dropbox': {
        'name': 'Dropbox',
        'slug': 'dropbox',
        'icon': 'dropbox',
        'color': '#0061FF',
        'category': 'cloud',
        'file_limit': '2GB',
        'file_limit_note': '2GB free storage total, 50GB with Plus',
        'users': '700 million',
        'share_method': 'link sharing',
        'share_instruction': 'SendFiles.Online is a simpler alternative to Dropbox for one-time transfers. No account required for recipients, and no storage limits to worry about.',
        'app_instruction': 'Compare with dropbox.com',
        'is_active': True,
    },
    'onedrive': {
        'name': 'OneDrive',
        'slug': 'onedrive',
        'icon': 'microsoft',
        'color': '#0078D4',
        'category': 'cloud',
        'file_limit': '250GB',
        'file_limit_note': '250GB per file with Office 365',
        'users': '250 million',
        'share_method': 'link sharing',
        'share_instruction': 'Skip OneDrive\'s complex sharing settings. Use SendFiles.Online to share large files with anyone - no Microsoft account required for your recipients.',
        'app_instruction': 'Compare with onedrive.com',
        'is_active': True,
    },
    'icloud': {
        'name': 'iCloud',
        'slug': 'icloud',
        'icon': 'apple',
        'color': '#3693F3',
        'category': 'cloud',
        'file_limit': '50GB',
        'file_limit_note': '50GB per file with iCloud Drive',
        'users': '850 million',
        'share_method': 'link sharing',
        'share_instruction': 'SendFiles.Online works on all devices, not just Apple. Share large files with anyone regardless of whether they use Apple products.',
        'app_instruction': 'Compare with icloud.com',
        'is_active': True,
    },

    # ==================== VIDEO & STREAMING ====================
    'youtube': {
        'name': 'YouTube',
        'slug': 'youtube',
        'icon': 'youtube',
        'color': '#FF0000',
        'category': 'social',
        'file_limit': '256GB',
        'file_limit_note': '256GB or 12 hours for verified accounts, 15 min otherwise',
        'users': '2.7 billion',
        'share_method': 'comment or community post',
        'share_instruction': 'Share your SendFiles.Online link in video comments, community posts, or video descriptions. Perfect for sharing project files, assets, or bonus content with your audience.',
        'app_instruction': 'Open YouTube and navigate to your video or community tab',
        'is_active': True,
    },
    'vimeo': {
        'name': 'Vimeo',
        'slug': 'vimeo',
        'icon': 'vimeo-v',
        'color': '#1AB7EA',
        'category': 'social',
        'file_limit': '500MB',
        'file_limit_note': '500MB/week on free plan, varies by subscription',
        'users': '260 million',
        'share_method': 'video description',
        'share_instruction': 'Add your SendFiles.Online link to video descriptions or comments. Great for sharing source files, behind-the-scenes content, or project assets with viewers.',
        'app_instruction': 'Open Vimeo and edit your video or post a comment',
        'is_active': True,
    },
    'dailymotion': {
        'name': 'Dailymotion',
        'slug': 'dailymotion',
        'icon': 'dailymotion',
        'color': '#0066DC',
        'category': 'social',
        'file_limit': '2GB',
        'file_limit_note': '2GB and 60 minutes per video',
        'users': '300 million',
        'share_method': 'video description',
        'share_instruction': 'Include your SendFiles.Online link in video descriptions or comments to share additional files with your audience.',
        'app_instruction': 'Open Dailymotion and navigate to your video',
        'is_active': True,
    },
    'rumble': {
        'name': 'Rumble',
        'slug': 'rumble',
        'icon': 'r',
        'color': '#85C742',
        'category': 'social',
        'file_limit': '15GB',
        'file_limit_note': '15GB per video',
        'users': '80 million',
        'share_method': 'video description',
        'share_instruction': 'Add your SendFiles.Online link to video descriptions or comments on Rumble to share supplementary files.',
        'app_instruction': 'Open Rumble and navigate to your video settings',
        'is_active': True,
    },

    # ==================== CREATIVE & ART PLATFORMS ====================
    'deviantart': {
        'name': 'DeviantArt',
        'slug': 'deviantart',
        'icon': 'deviantart',
        'color': '#05CC47',
        'category': 'social',
        'file_limit': '200MB',
        'file_limit_note': '200MB for images, 300MB for videos',
        'users': '61 million',
        'share_method': 'deviation description or comment',
        'share_instruction': 'Add your SendFiles.Online link to deviation descriptions, journals, or comments. Perfect for sharing high-resolution artwork, PSD files, or resource packs.',
        'app_instruction': 'Open DeviantArt and edit your submission',
        'is_active': True,
    },
    'artstation': {
        'name': 'ArtStation',
        'slug': 'artstation',
        'icon': 'artstation',
        'color': '#13AFF0',
        'category': 'social',
        'file_limit': '200MB',
        'file_limit_note': '200MB per file',
        'users': '20 million',
        'share_method': 'project description',
        'share_instruction': 'Include your SendFiles.Online link in project descriptions to share source files, 3D models, or high-resolution renders with other artists.',
        'app_instruction': 'Open ArtStation and edit your project',
        'is_active': True,
    },
    'behance': {
        'name': 'Behance',
        'slug': 'behance',
        'icon': 'behance',
        'color': '#1769FF',
        'category': 'social',
        'file_limit': '25MB',
        'file_limit_note': '25MB per image, 1GB for video',
        'users': '40 million',
        'share_method': 'project description',
        'share_instruction': 'Add your SendFiles.Online link to project descriptions to share design source files, mockups, or additional assets with viewers.',
        'app_instruction': 'Open Behance and edit your project',
        'is_active': True,
    },
    'dribbble': {
        'name': 'Dribbble',
        'slug': 'dribbble',
        'icon': 'dribbble',
        'color': '#EA4C89',
        'category': 'social',
        'file_limit': '50MB',
        'file_limit_note': '50MB for videos',
        'users': '10 million',
        'share_method': 'shot description',
        'share_instruction': 'Include your SendFiles.Online link in shot descriptions to share design files, templates, or full project assets with the design community.',
        'app_instruction': 'Open Dribbble and edit your shot',
        'is_active': True,
    },
    'pixiv': {
        'name': 'Pixiv',
        'slug': 'pixiv',
        'icon': 'p',
        'color': '#0096FA',
        'category': 'social',
        'file_limit': '32MB',
        'file_limit_note': '32MB per image',
        'users': '84 million',
        'share_method': 'caption or fanbox',
        'share_instruction': 'Add your SendFiles.Online link to illustration captions or Fanbox posts to share high-resolution artwork or resource files.',
        'app_instruction': 'Open Pixiv and edit your illustration',
        'is_active': True,
    },

    # ==================== MUSIC PLATFORMS ====================
    'soundcloud': {
        'name': 'SoundCloud',
        'slug': 'soundcloud',
        'icon': 'soundcloud',
        'color': '#FF5500',
        'category': 'social',
        'file_limit': '500MB',
        'file_limit_note': '500MB and 5GB total on free plan',
        'users': '175 million',
        'share_method': 'track description or comment',
        'share_instruction': 'Add your SendFiles.Online link to track descriptions or comments to share stems, project files, or additional audio content.',
        'app_instruction': 'Open SoundCloud and edit your track',
        'is_active': True,
    },
    'bandcamp': {
        'name': 'Bandcamp',
        'slug': 'bandcamp',
        'icon': 'bandcamp',
        'color': '#629AA9',
        'category': 'social',
        'file_limit': '291MB',
        'file_limit_note': '291MB per track (FLAC/WAV)',
        'users': '7 million',
        'share_method': 'album description',
        'share_instruction': 'Include your SendFiles.Online link in album or track descriptions to share bonus content, stems, or supplementary files with your fans.',
        'app_instruction': 'Open Bandcamp and edit your release',
        'is_active': True,
    },
    'spotify': {
        'name': 'Spotify',
        'slug': 'spotify',
        'icon': 'spotify',
        'color': '#1DB954',
        'category': 'social',
        'file_limit': 'N/A',
        'file_limit_note': 'No file sharing feature',
        'users': '600 million',
        'share_method': 'bio link or social share',
        'share_instruction': 'Add your SendFiles.Online link to your artist bio or share it alongside Spotify links to give fans access to bonus content, stems, or exclusive files.',
        'app_instruction': 'Edit your Spotify for Artists profile or share via social media',
        'is_active': True,
    },

    # ==================== IMAGE HOSTING ====================
    'imgur': {
        'name': 'Imgur',
        'slug': 'imgur',
        'icon': 'images',
        'color': '#1BB76E',
        'category': 'social',
        'file_limit': '20MB',
        'file_limit_note': '20MB for images, 200MB for videos',
        'users': '300 million',
        'share_method': 'description or comment',
        'share_instruction': 'Add your SendFiles.Online link to image descriptions or comments to share original high-resolution files or related content.',
        'app_instruction': 'Open Imgur and edit your post',
        'is_active': True,
    },
    'flickr': {
        'name': 'Flickr',
        'slug': 'flickr',
        'icon': 'flickr',
        'color': '#0063DC',
        'category': 'social',
        'file_limit': '200MB',
        'file_limit_note': '200MB per photo',
        'users': '90 million',
        'share_method': 'photo description',
        'share_instruction': 'Include your SendFiles.Online link in photo descriptions to share RAW files, full-resolution versions, or related content.',
        'app_instruction': 'Open Flickr and edit your photo',
        'is_active': True,
    },
    'unsplash': {
        'name': 'Unsplash',
        'slug': 'unsplash',
        'icon': 'unsplash',
        'color': '#000000',
        'category': 'social',
        'file_limit': '30MB',
        'file_limit_note': '30MB recommended, larger files allowed',
        'users': '330 million',
        'share_method': 'profile link',
        'share_instruction': 'Share your SendFiles.Online link in your Unsplash profile to offer RAW files, presets, or other resources to people who download your photos.',
        'app_instruction': 'Edit your Unsplash profile',
        'is_active': True,
    },

    # ==================== CREATOR PLATFORMS ====================
    'patreon': {
        'name': 'Patreon',
        'slug': 'patreon',
        'icon': 'patreon',
        'color': '#FF424D',
        'category': 'professional',
        'file_limit': '200MB',
        'file_limit_note': '200MB per attachment',
        'users': '250 million',
        'share_method': 'post attachment or link',
        'share_instruction': 'Add your SendFiles.Online link to Patreon posts to share large files like 4K videos, PSD files, or resource packs that exceed Patreon\'s limits.',
        'app_instruction': 'Create a new Patreon post',
        'is_active': True,
    },
    'ko-fi': {
        'name': 'Ko-fi',
        'slug': 'ko-fi',
        'icon': 'coffee',
        'color': '#FF5E5B',
        'category': 'professional',
        'file_limit': '25MB',
        'file_limit_note': '25MB for gallery items',
        'users': '1 million',
        'share_method': 'post or shop link',
        'share_instruction': 'Include your SendFiles.Online link in Ko-fi posts or shop descriptions to deliver large files to supporters.',
        'app_instruction': 'Create a new Ko-fi post',
        'is_active': True,
    },
    'gumroad': {
        'name': 'Gumroad',
        'slug': 'gumroad',
        'icon': 'shopping-cart',
        'color': '#FF90E8',
        'category': 'professional',
        'file_limit': '16GB',
        'file_limit_note': '16GB per product, limited downloads',
        'users': '10 million',
        'share_method': 'product description',
        'share_instruction': 'Use SendFiles.Online links in product descriptions or delivery emails for an alternative file delivery method that doesn\'t count against your limits.',
        'app_instruction': 'Edit your Gumroad product',
        'is_active': True,
    },

    # ==================== REGIONAL PLATFORMS ====================
    'vk': {
        'name': 'VK (VKontakte)',
        'slug': 'vk',
        'icon': 'vk',
        'color': '#4680C2',
        'category': 'social',
        'file_limit': '200MB',
        'file_limit_note': '200MB for documents',
        'users': '100 million',
        'share_method': 'post or message',
        'share_instruction': 'Share your SendFiles.Online link in VK posts, messages, or group discussions. Great for sharing larger files with Russian-speaking audiences.',
        'app_instruction': 'Open VK and create a post or message',
        'is_active': True,
    },
    'bluesky': {
        'name': 'Bluesky',
        'slug': 'bluesky',
        'icon': 'cloud',
        'color': '#0085FF',
        'category': 'social',
        'file_limit': '1MB',
        'file_limit_note': '1MB for images',
        'users': '10 million',
        'share_method': 'post',
        'share_instruction': 'Post your SendFiles.Online link on Bluesky to share larger files with your followers. Perfect for sharing high-res images or documents.',
        'app_instruction': 'Open Bluesky and create a post',
        'is_active': True,
    },
    'mastodon': {
        'name': 'Mastodon',
        'slug': 'mastodon',
        'icon': 'mastodon',
        'color': '#6364FF',
        'category': 'social',
        'file_limit': '40MB',
        'file_limit_note': '40MB for media, varies by instance',
        'users': '10 million',
        'share_method': 'toot',
        'share_instruction': 'Share your SendFiles.Online link in a Mastodon post (toot) to share larger files across the fediverse.',
        'app_instruction': 'Open your Mastodon instance and create a post',
        'is_active': True,
    },

    # ==================== FORUM & COMMUNITY ====================
    'discourse': {
        'name': 'Discourse Forums',
        'slug': 'discourse',
        'icon': 'discourse',
        'color': '#000000',
        'category': 'professional',
        'file_limit': '4MB',
        'file_limit_note': '4MB default, varies by forum',
        'users': 'millions',
        'share_method': 'post',
        'share_instruction': 'Add your SendFiles.Online link to forum posts when you need to share files larger than the forum allows.',
        'app_instruction': 'Navigate to your Discourse forum',
        'is_active': True,
    },
    'quora': {
        'name': 'Quora',
        'slug': 'quora',
        'icon': 'quora',
        'color': '#B92B27',
        'category': 'social',
        'file_limit': 'N/A',
        'file_limit_note': 'Images only, no file uploads',
        'users': '400 million',
        'share_method': 'answer or post',
        'share_instruction': 'Include your SendFiles.Online link in Quora answers or posts to share supplementary files, documents, or resources.',
        'app_instruction': 'Open Quora and write an answer',
        'is_active': True,
    },

    # ==================== OTHER PLATFORMS ====================
    'sms': {
        'name': 'SMS / Text Message',
        'slug': 'sms',
        'icon': 'comment-sms',
        'color': '#34C759',
        'category': 'messaging',
        'file_limit': '300KB',
        'file_limit_note': '300KB for MMS, varies by carrier',
        'users': 'billions',
        'share_method': 'text message',
        'share_instruction': 'Send your SendFiles.Online link via regular text message (SMS). Works on any phone, no app required. Your recipient just taps the link to download.',
        'app_instruction': 'Open your default messaging app',
        'is_active': True,
    },
    'email': {
        'name': 'Email',
        'slug': 'email',
        'icon': 'envelope',
        'color': '#6B7280',
        'category': 'email',
        'file_limit': '25MB',
        'file_limit_note': 'Most providers limit to 20-25MB',
        'users': '4 billion',
        'share_method': 'email',
        'share_instruction': 'Include your SendFiles.Online link in any email. Works with all email providers and avoids attachment limits, bounced emails, and inbox clutter.',
        'app_instruction': 'Open your email client',
        'is_active': True,
    },
}


def get_platform(slug):
    """Get a single platform by slug."""
    return PLATFORMS.get(slug)


def get_all_platforms():
    """Get all active platforms."""
    return {k: v for k, v in PLATFORMS.items() if v.get('is_active', True)}


def get_platforms_by_category():
    """Get platforms organized by category."""
    platforms_by_cat = {}
    for slug, platform in PLATFORMS.items():
        if not platform.get('is_active', True):
            continue
        category = platform.get('category', 'other')
        if category not in platforms_by_cat:
            platforms_by_cat[category] = []
        platforms_by_cat[category].append({**platform, 'slug': slug})

    # Sort by category order
    sorted_cats = sorted(
        platforms_by_cat.items(),
        key=lambda x: PLATFORM_CATEGORIES.get(x[0], {}).get('order', 99)
    )
    return dict(sorted_cats)


def get_related_platforms(current_slug, limit=6):
    """Get related platforms (same category, then others)."""
    current = PLATFORMS.get(current_slug)
    if not current:
        return []

    current_cat = current.get('category')
    related = []

    # First, add platforms from same category
    for slug, platform in PLATFORMS.items():
        if slug != current_slug and platform.get('category') == current_cat and platform.get('is_active', True):
            related.append({**platform, 'slug': slug})

    # Then add from other categories
    for slug, platform in PLATFORMS.items():
        if slug != current_slug and platform.get('category') != current_cat and platform.get('is_active', True):
            related.append({**platform, 'slug': slug})

    return related[:limit]


def generate_faqs(platform):
    """Generate FAQs for a platform."""
    name = platform['name']
    limit = platform['file_limit']

    return [
        {
            'question': f'How do I send large files on {name}?',
            'answer': f'Upload your files to SendFiles.Online (up to 10GB free), copy the download link, and share it on {name}. Your recipient can download directly without any account.'
        },
        {
            'question': f'What is the file size limit on {name}?',
            'answer': f'{name} has a file size limit of {limit}. SendFiles.Online lets you bypass this limitation by sharing a download link instead of the actual file.'
        },
        {
            'question': f'Can I send files larger than {limit} on {name}?',
            'answer': f'Yes! While {name} limits direct file sharing to {limit}, you can use SendFiles.Online to share files up to 10GB. Just upload your files, get a link, and share it on {name}.'
        },
        {
            'question': f'Is it free to send large files on {name}?',
            'answer': f'Yes, SendFiles.Online offers free transfers up to 10GB with 14-day storage. Upload your files, share the link on {name}, and your recipients can download for free.'
        },
        {
            'question': 'How long do shared files stay available?',
            'answer': 'Free transfers on SendFiles.Online are available for 14 days. Your recipients can download the files as many times as needed during this period.'
        },
        {
            'question': f'Can I password protect files I share on {name}?',
            'answer': 'Yes! When uploading to SendFiles.Online, you can add password protection. Only recipients with the password can download the files.'
        },
        {
            'question': 'Do recipients need to create an account?',
            'answer': 'No. Recipients just click your SendFiles.Online link and download directly. No signup, no account, no app installation required.'
        },
    ]
