"""
Platform configuration for dynamic "Send Large Files on {Platform}" pages.
This enables long-tail SEO targeting searches like "how to send large files on whatsapp".
"""

PLATFORM_CATEGORIES = {
    'messaging': {
        'name': 'Messaging Apps',
        'description': 'Popular messaging and chat applications',
        'order': 1,
    },
    'social': {
        'name': 'Social Media',
        'description': 'Social networking platforms',
        'order': 2,
    },
    'email': {
        'name': 'Email Services',
        'description': 'Email providers and clients',
        'order': 3,
    },
    'professional': {
        'name': 'Professional & Business',
        'description': 'Workplace collaboration tools',
        'order': 4,
    },
    'dating': {
        'name': 'Dating Apps',
        'description': 'Dating and social connection apps',
        'order': 5,
    },
    'gaming': {
        'name': 'Gaming Platforms',
        'description': 'Gaming and streaming platforms',
        'order': 6,
    },
    'cloud': {
        'name': 'Cloud Storage',
        'description': 'Cloud storage and file hosting services',
        'order': 7,
    },
}

PLATFORMS = {
    # ==================== MESSAGING APPS ====================
    'whatsapp': {
        'name': 'WhatsApp',
        'slug': 'whatsapp',
        'icon': 'whatsapp',
        'color': '#25D366',
        'category': 'messaging',
        'file_limit': '2GB',
        'file_limit_note': '2GB per file, but quality is compressed',
        'users': '2 billion',
        'share_method': 'chat message',
        'share_instruction': 'Open any chat conversation, tap the message field, paste your SendFiles.Online link, and tap send. Your recipient can tap the link to download instantly.',
        'app_instruction': 'Open WhatsApp on your phone or WhatsApp Web on your computer',
        'is_active': True,
    },
    'facebook-messenger': {
        'name': 'Facebook Messenger',
        'slug': 'facebook-messenger',
        'icon': 'facebook-messenger',
        'color': '#0084FF',
        'category': 'messaging',
        'file_limit': '25MB',
        'file_limit_note': '25MB for most file types',
        'users': '1 billion',
        'share_method': 'message',
        'share_instruction': 'Open a Messenger conversation, paste your SendFiles.Online link in the message box, and hit send. The link will appear as a clickable preview.',
        'app_instruction': 'Open Messenger app or messenger.com in your browser',
        'is_active': True,
    },
    'telegram': {
        'name': 'Telegram',
        'slug': 'telegram',
        'icon': 'telegram',
        'color': '#0088CC',
        'category': 'messaging',
        'file_limit': '2GB',
        'file_limit_note': '2GB per file with Telegram Premium, 1.5GB for free users',
        'users': '800 million',
        'share_method': 'message',
        'share_instruction': 'Open any Telegram chat, paste your SendFiles.Online link, and send. Telegram will show a rich link preview automatically.',
        'app_instruction': 'Open Telegram on any device - mobile, desktop, or web',
        'is_active': True,
    },
    'signal': {
        'name': 'Signal',
        'slug': 'signal',
        'icon': 'signal',
        'color': '#3A76F0',
        'category': 'messaging',
        'file_limit': '100MB',
        'file_limit_note': '100MB per attachment',
        'users': '40 million',
        'share_method': 'message',
        'share_instruction': 'Open a Signal conversation, paste your SendFiles.Online link, and send. Your contact will receive a secure, clickable link.',
        'app_instruction': 'Open Signal on your phone or Signal Desktop',
        'is_active': True,
    },
    'imessage': {
        'name': 'iMessage',
        'slug': 'imessage',
        'icon': 'apple',
        'color': '#34C759',
        'category': 'messaging',
        'file_limit': '100MB',
        'file_limit_note': '100MB, larger files sent via iCloud link',
        'users': '1.3 billion',
        'share_method': 'text message',
        'share_instruction': 'Open Messages on your iPhone, iPad, or Mac. Start a conversation, paste your SendFiles.Online link, and send. Works for both iMessage and SMS recipients.',
        'app_instruction': 'Open the Messages app on any Apple device',
        'is_active': True,
    },
    'discord': {
        'name': 'Discord',
        'slug': 'discord',
        'icon': 'discord',
        'color': '#5865F2',
        'category': 'messaging',
        'file_limit': '25MB',
        'file_limit_note': '25MB free, 500MB with Nitro',
        'users': '200 million',
        'share_method': 'message',
        'share_instruction': 'Open any Discord channel or DM, paste your SendFiles.Online link, and send. Discord will embed a preview of your transfer.',
        'app_instruction': 'Open Discord app or discord.com',
        'is_active': True,
    },
    'slack': {
        'name': 'Slack',
        'slug': 'slack',
        'icon': 'slack',
        'color': '#4A154B',
        'category': 'messaging',
        'file_limit': '1GB',
        'file_limit_note': '1GB per file on paid plans, limited storage on free',
        'users': '32 million',
        'share_method': 'message',
        'share_instruction': 'Open any Slack channel or direct message, paste your SendFiles.Online link, and send. Slack will unfurl the link with a preview.',
        'app_instruction': 'Open Slack on desktop, mobile, or web',
        'is_active': True,
    },
    'microsoft-teams': {
        'name': 'Microsoft Teams',
        'slug': 'microsoft-teams',
        'icon': 'microsoft',
        'color': '#6264A7',
        'category': 'messaging',
        'file_limit': '250GB',
        'file_limit_note': '250GB per file, but requires Office 365',
        'users': '320 million',
        'share_method': 'message',
        'share_instruction': 'Open a Teams chat or channel, paste your SendFiles.Online link in the message box, and send. Anyone in the conversation can click to download.',
        'app_instruction': 'Open Microsoft Teams app or teams.microsoft.com',
        'is_active': True,
    },
    'wechat': {
        'name': 'WeChat',
        'slug': 'wechat',
        'icon': 'weixin',
        'color': '#07C160',
        'category': 'messaging',
        'file_limit': '100MB',
        'file_limit_note': '100MB for files, 25MB for videos',
        'users': '1.3 billion',
        'share_method': 'message',
        'share_instruction': 'Open a WeChat conversation, paste your SendFiles.Online link, and send. Your contact can tap the link to download the files.',
        'app_instruction': 'Open WeChat on your mobile device',
        'is_active': True,
    },
    'line': {
        'name': 'LINE',
        'slug': 'line',
        'icon': 'line',
        'color': '#00B900',
        'category': 'messaging',
        'file_limit': '300MB',
        'file_limit_note': '300MB per file',
        'users': '178 million',
        'share_method': 'message',
        'share_instruction': 'Open a LINE chat, paste your SendFiles.Online link, and send. LINE will display a link preview for easy access.',
        'app_instruction': 'Open LINE app on mobile or desktop',
        'is_active': True,
    },
    'viber': {
        'name': 'Viber',
        'slug': 'viber',
        'icon': 'viber',
        'color': '#7360F2',
        'category': 'messaging',
        'file_limit': '200MB',
        'file_limit_note': '200MB per file',
        'users': '260 million',
        'share_method': 'message',
        'share_instruction': 'Open a Viber chat, paste your SendFiles.Online link, and send. Your recipient will see a tappable link to download.',
        'app_instruction': 'Open Viber on mobile or desktop',
        'is_active': True,
    },
    'snapchat': {
        'name': 'Snapchat',
        'slug': 'snapchat',
        'icon': 'snapchat',
        'color': '#FFFC00',
        'text_color': '#000000',
        'category': 'messaging',
        'file_limit': '2.5MB',
        'file_limit_note': '2.5MB for snaps, 64MB for memories',
        'users': '800 million',
        'share_method': 'chat',
        'share_instruction': 'Open a Snapchat chat conversation, paste your SendFiles.Online link, and send. Your friend can tap the link to view and download files.',
        'app_instruction': 'Open Snapchat and go to the Chat section',
        'is_active': True,
    },
    'skype': {
        'name': 'Skype',
        'slug': 'skype',
        'icon': 'skype',
        'color': '#00AFF0',
        'category': 'messaging',
        'file_limit': '300MB',
        'file_limit_note': '300MB per file',
        'users': '300 million',
        'share_method': 'message',
        'share_instruction': 'Open a Skype conversation, paste your SendFiles.Online link in the chat, and send. The link will be clickable for all participants.',
        'app_instruction': 'Open Skype on desktop, mobile, or web',
        'is_active': True,
    },

    # ==================== SOCIAL MEDIA ====================
    'instagram': {
        'name': 'Instagram',
        'slug': 'instagram',
        'icon': 'instagram',
        'color': '#E4405F',
        'category': 'social',
        'file_limit': '650MB',
        'file_limit_note': '650MB for Reels, no file sharing in DMs',
        'users': '2 billion',
        'share_method': 'direct message',
        'share_instruction': 'Open Instagram DMs, start or open a conversation, paste your SendFiles.Online link, and send. Instagram will show a tappable link for your recipient.',
        'app_instruction': 'Open Instagram app and tap the messenger icon',
        'is_active': True,
    },
    'facebook': {
        'name': 'Facebook',
        'slug': 'facebook',
        'icon': 'facebook',
        'color': '#1877F2',
        'category': 'social',
        'file_limit': '25MB',
        'file_limit_note': '25MB for attachments in posts and messages',
        'users': '3 billion',
        'share_method': 'post or message',
        'share_instruction': 'Share your SendFiles.Online link in a Facebook post, comment, or send it via Messenger. Facebook will display a rich preview with your transfer details.',
        'app_instruction': 'Open Facebook app or facebook.com',
        'is_active': True,
    },
    'twitter': {
        'name': 'X (Twitter)',
        'slug': 'twitter',
        'icon': 'x-twitter',
        'color': '#000000',
        'category': 'social',
        'file_limit': '15MB',
        'file_limit_note': '15MB for images, 512MB for video with Premium',
        'users': '600 million',
        'share_method': 'tweet or DM',
        'share_instruction': 'Tweet your SendFiles.Online link or send it in a direct message. X will display a link card preview so your followers know what to expect.',
        'app_instruction': 'Open X (Twitter) app or x.com',
        'is_active': True,
    },
    'tiktok': {
        'name': 'TikTok',
        'slug': 'tiktok',
        'icon': 'tiktok',
        'color': '#000000',
        'category': 'social',
        'file_limit': '287MB',
        'file_limit_note': '287MB for videos, no file sharing feature',
        'users': '1.5 billion',
        'share_method': 'direct message or bio',
        'share_instruction': 'Send your SendFiles.Online link via TikTok DM, or add it to your bio for your followers. Recipients can tap the link to download your files.',
        'app_instruction': 'Open TikTok app and go to messages or your profile',
        'is_active': True,
    },
    'linkedin': {
        'name': 'LinkedIn',
        'slug': 'linkedin',
        'icon': 'linkedin',
        'color': '#0A66C2',
        'category': 'social',
        'file_limit': '100MB',
        'file_limit_note': '100MB for documents, 5GB for videos',
        'users': '1 billion',
        'share_method': 'post or message',
        'share_instruction': 'Share your SendFiles.Online link in a LinkedIn post or send it via LinkedIn messaging. Perfect for sharing large presentations, portfolios, or work files professionally.',
        'app_instruction': 'Open LinkedIn app or linkedin.com',
        'is_active': True,
    },
    'reddit': {
        'name': 'Reddit',
        'slug': 'reddit',
        'icon': 'reddit',
        'color': '#FF4500',
        'category': 'social',
        'file_limit': '20MB',
        'file_limit_note': '20MB for images, 1GB for videos',
        'users': '1.7 billion',
        'share_method': 'post or comment',
        'share_instruction': 'Share your SendFiles.Online link in a Reddit post, comment, or direct message. Other Redditors can click through to download your shared files.',
        'app_instruction': 'Open Reddit app or reddit.com',
        'is_active': True,
    },
    'pinterest': {
        'name': 'Pinterest',
        'slug': 'pinterest',
        'icon': 'pinterest',
        'color': '#E60023',
        'category': 'social',
        'file_limit': '20MB',
        'file_limit_note': '20MB for images',
        'users': '480 million',
        'share_method': 'message',
        'share_instruction': 'Send your SendFiles.Online link via Pinterest messages or add it to a pin description. Great for sharing high-resolution design files or project assets.',
        'app_instruction': 'Open Pinterest app or pinterest.com',
        'is_active': True,
    },
    'threads': {
        'name': 'Threads',
        'slug': 'threads',
        'icon': 'threads',
        'color': '#000000',
        'category': 'social',
        'file_limit': '10MB',
        'file_limit_note': 'Limited file support, image-focused',
        'users': '200 million',
        'share_method': 'post',
        'share_instruction': 'Post your SendFiles.Online link on Threads. Your followers can tap the link to access and download your shared files.',
        'app_instruction': 'Open Threads app',
        'is_active': True,
    },
    'tumblr': {
        'name': 'Tumblr',
        'slug': 'tumblr',
        'icon': 'tumblr',
        'color': '#36465D',
        'category': 'social',
        'file_limit': '100MB',
        'file_limit_note': '100MB for videos, 20MB for images',
        'users': '135 million',
        'share_method': 'post',
        'share_instruction': 'Create a Tumblr post with your SendFiles.Online link. Perfect for sharing large art files, videos, or creative projects with your followers.',
        'app_instruction': 'Open Tumblr app or tumblr.com',
        'is_active': True,
    },

    # ==================== EMAIL SERVICES ====================
    'gmail': {
        'name': 'Gmail',
        'slug': 'gmail',
        'icon': 'google',
        'color': '#EA4335',
        'category': 'email',
        'file_limit': '25MB',
        'file_limit_note': '25MB total per email including all attachments',
        'users': '1.8 billion',
        'share_method': 'email',
        'share_instruction': 'Compose a new email in Gmail, paste your SendFiles.Online link in the body, and send. Much easier than dealing with attachment limits or Google Drive sharing settings.',
        'app_instruction': 'Open Gmail app or gmail.com',
        'is_active': True,
    },
    'outlook': {
        'name': 'Outlook',
        'slug': 'outlook',
        'icon': 'microsoft',
        'color': '#0078D4',
        'category': 'email',
        'file_limit': '20MB',
        'file_limit_note': '20MB for Outlook.com, varies for Office 365',
        'users': '400 million',
        'share_method': 'email',
        'share_instruction': 'Compose an email in Outlook, paste your SendFiles.Online link, and send. Avoid attachment limits and ensure your recipient can access files regardless of their email provider.',
        'app_instruction': 'Open Outlook app or outlook.com',
        'is_active': True,
    },
    'yahoo-mail': {
        'name': 'Yahoo Mail',
        'slug': 'yahoo-mail',
        'icon': 'yahoo',
        'color': '#6001D2',
        'category': 'email',
        'file_limit': '25MB',
        'file_limit_note': '25MB total per email',
        'users': '225 million',
        'share_method': 'email',
        'share_instruction': 'Compose an email in Yahoo Mail, paste your SendFiles.Online link, and send. Your recipient can download files with a single click.',
        'app_instruction': 'Open Yahoo Mail app or mail.yahoo.com',
        'is_active': True,
    },
    'protonmail': {
        'name': 'ProtonMail',
        'slug': 'protonmail',
        'icon': 'envelope',
        'color': '#6D4AFF',
        'category': 'email',
        'file_limit': '25MB',
        'file_limit_note': '25MB on free plan',
        'users': '100 million',
        'share_method': 'email',
        'share_instruction': 'Compose a secure email in ProtonMail, paste your SendFiles.Online link, and send. Combine ProtonMail\'s encryption with our secure file transfers.',
        'app_instruction': 'Open ProtonMail app or mail.proton.me',
        'is_active': True,
    },
    'apple-mail': {
        'name': 'Apple Mail',
        'slug': 'apple-mail',
        'icon': 'apple',
        'color': '#007AFF',
        'category': 'email',
        'file_limit': '20MB',
        'file_limit_note': '20MB default, Mail Drop for larger files up to 5GB',
        'users': '500 million',
        'share_method': 'email',
        'share_instruction': 'Compose an email in Apple Mail, paste your SendFiles.Online link, and send. Works seamlessly on iPhone, iPad, and Mac.',
        'app_instruction': 'Open Mail app on any Apple device',
        'is_active': True,
    },
    'zoho-mail': {
        'name': 'Zoho Mail',
        'slug': 'zoho-mail',
        'icon': 'envelope',
        'color': '#C8202B',
        'category': 'email',
        'file_limit': '25MB',
        'file_limit_note': '25MB per email',
        'users': '15 million',
        'share_method': 'email',
        'share_instruction': 'Compose an email in Zoho Mail, paste your SendFiles.Online link, and send. Perfect for business file sharing without attachment hassles.',
        'app_instruction': 'Open Zoho Mail app or mail.zoho.com',
        'is_active': True,
    },

    # ==================== PROFESSIONAL & BUSINESS ====================
    'zoom': {
        'name': 'Zoom',
        'slug': 'zoom',
        'icon': 'video',
        'color': '#2D8CFF',
        'category': 'professional',
        'file_limit': '1GB',
        'file_limit_note': '1GB for cloud recordings, 512MB for chat files',
        'users': '300 million',
        'share_method': 'chat or meeting',
        'share_instruction': 'Share your SendFiles.Online link in Zoom chat during a meeting, or paste it in Team Chat. All participants can click to download the files.',
        'app_instruction': 'Open Zoom app and go to chat or start a meeting',
        'is_active': True,
    },
    'google-meet': {
        'name': 'Google Meet',
        'slug': 'google-meet',
        'icon': 'google',
        'color': '#00897B',
        'category': 'professional',
        'file_limit': 'N/A',
        'file_limit_note': 'No direct file sharing in Meet',
        'users': '300 million',
        'share_method': 'chat',
        'share_instruction': 'During a Google Meet call, open the in-meeting chat and paste your SendFiles.Online link. Or share via Google Chat before/after the meeting.',
        'app_instruction': 'Join a Google Meet call and open the chat panel',
        'is_active': True,
    },
    'notion': {
        'name': 'Notion',
        'slug': 'notion',
        'icon': 'n',
        'color': '#000000',
        'category': 'professional',
        'file_limit': '5MB',
        'file_limit_note': '5MB on free plan, unlimited on paid',
        'users': '35 million',
        'share_method': 'page or database',
        'share_instruction': 'Add your SendFiles.Online link to any Notion page, database, or comment. Notion will display it as a bookmark with a preview.',
        'app_instruction': 'Open Notion app or notion.so',
        'is_active': True,
    },
    'trello': {
        'name': 'Trello',
        'slug': 'trello',
        'icon': 'trello',
        'color': '#0052CC',
        'category': 'professional',
        'file_limit': '10MB',
        'file_limit_note': '10MB on free plan, 250MB on paid',
        'users': '50 million',
        'share_method': 'card',
        'share_instruction': 'Add your SendFiles.Online link to a Trello card description, comment, or attachment. Team members can click to download associated files.',
        'app_instruction': 'Open Trello and navigate to your board',
        'is_active': True,
    },
    'asana': {
        'name': 'Asana',
        'slug': 'asana',
        'icon': 'check-circle',
        'color': '#F06A6A',
        'category': 'professional',
        'file_limit': '100MB',
        'file_limit_note': '100MB per attachment',
        'users': '140 million',
        'share_method': 'task or comment',
        'share_instruction': 'Add your SendFiles.Online link to any Asana task description or comment. Perfect for sharing large project files with your team.',
        'app_instruction': 'Open Asana app or app.asana.com',
        'is_active': True,
    },
    'jira': {
        'name': 'Jira',
        'slug': 'jira',
        'icon': 'jira',
        'color': '#0052CC',
        'category': 'professional',
        'file_limit': '10MB',
        'file_limit_note': '10MB per attachment on cloud',
        'users': '10 million',
        'share_method': 'issue or comment',
        'share_instruction': 'Add your SendFiles.Online link to a Jira issue description or comment. Great for sharing large log files, screenshots, or documentation with your development team.',
        'app_instruction': 'Open Jira and navigate to your project',
        'is_active': True,
    },
    'github': {
        'name': 'GitHub',
        'slug': 'github',
        'icon': 'github',
        'color': '#181717',
        'category': 'professional',
        'file_limit': '100MB',
        'file_limit_note': '100MB per file, 50MB for web uploads',
        'users': '100 million',
        'share_method': 'issue, PR, or comment',
        'share_instruction': 'Add your SendFiles.Online link to a GitHub issue, pull request, or comment. Perfect for sharing large binaries, test files, or assets that shouldn\'t be in the repo.',
        'app_instruction': 'Open GitHub and navigate to your repository',
        'is_active': True,
    },
    'confluence': {
        'name': 'Confluence',
        'slug': 'confluence',
        'icon': 'confluence',
        'color': '#172B4D',
        'category': 'professional',
        'file_limit': '10MB',
        'file_limit_note': '10MB per attachment on cloud',
        'users': '75,000 teams',
        'share_method': 'page',
        'share_instruction': 'Embed your SendFiles.Online link in any Confluence page. Confluence will display a smart link card for easy access.',
        'app_instruction': 'Open Confluence and edit a page',
        'is_active': True,
    },
    'monday': {
        'name': 'Monday.com',
        'slug': 'monday',
        'icon': 'calendar-check',
        'color': '#FF3D57',
        'category': 'professional',
        'file_limit': '500MB',
        'file_limit_note': '500MB per file',
        'users': '225,000 teams',
        'share_method': 'item or update',
        'share_instruction': 'Add your SendFiles.Online link to any Monday item or update. Team members can access large files directly from your workflow.',
        'app_instruction': 'Open Monday.com and navigate to your board',
        'is_active': True,
    },
    'basecamp': {
        'name': 'Basecamp',
        'slug': 'basecamp',
        'icon': 'campground',
        'color': '#1D2D35',
        'category': 'professional',
        'file_limit': 'Unlimited',
        'file_limit_note': 'No limit, but can be slow for very large files',
        'users': 'millions',
        'share_method': 'message or docs',
        'share_instruction': 'Share your SendFiles.Online link in Basecamp messages or Docs & Files. Fast and reliable large file sharing for your team.',
        'app_instruction': 'Open Basecamp and navigate to your project',
        'is_active': True,
    },

    # ==================== DATING APPS ====================
    'tinder': {
        'name': 'Tinder',
        'slug': 'tinder',
        'icon': 'fire',
        'color': '#FE3C72',
        'category': 'dating',
        'file_limit': 'N/A',
        'file_limit_note': 'No file sharing, limited to photos',
        'users': '75 million',
        'share_method': 'message',
        'share_instruction': 'Send your SendFiles.Online link in a Tinder chat. Perfect for sharing photos, playlists, or other files with your match safely.',
        'app_instruction': 'Open Tinder and go to your matches',
        'is_active': True,
    },
    'bumble': {
        'name': 'Bumble',
        'slug': 'bumble',
        'icon': 'bee',
        'color': '#FFC629',
        'text_color': '#000000',
        'category': 'dating',
        'file_limit': 'N/A',
        'file_limit_note': 'No file sharing feature',
        'users': '45 million',
        'share_method': 'message',
        'share_instruction': 'Share your SendFiles.Online link in a Bumble conversation. A safe way to share photos or files with new connections.',
        'app_instruction': 'Open Bumble and go to your conversations',
        'is_active': True,
    },
    'hinge': {
        'name': 'Hinge',
        'slug': 'hinge',
        'icon': 'heart',
        'color': '#F24C86',
        'category': 'dating',
        'file_limit': 'N/A',
        'file_limit_note': 'No file sharing feature',
        'users': '23 million',
        'share_method': 'message',
        'share_instruction': 'Send your SendFiles.Online link in a Hinge chat to share photos, videos, or other files with your potential match.',
        'app_instruction': 'Open Hinge and go to your matches',
        'is_active': True,
    },

    # ==================== GAMING PLATFORMS ====================
    'steam': {
        'name': 'Steam',
        'slug': 'steam',
        'icon': 'steam',
        'color': '#171A21',
        'category': 'gaming',
        'file_limit': 'N/A',
        'file_limit_note': 'No file sharing in chat',
        'users': '120 million',
        'share_method': 'chat',
        'share_instruction': 'Send your SendFiles.Online link via Steam Chat to share game mods, screenshots, or other files with your gaming friends.',
        'app_instruction': 'Open Steam and go to Friends & Chat',
        'is_active': True,
    },
    'playstation': {
        'name': 'PlayStation',
        'slug': 'playstation',
        'icon': 'playstation',
        'color': '#003791',
        'category': 'gaming',
        'file_limit': 'N/A',
        'file_limit_note': 'No file sharing feature',
        'users': '108 million',
        'share_method': 'message',
        'share_instruction': 'Send your SendFiles.Online link via PlayStation messages to share game clips, screenshots, or files with your PSN friends.',
        'app_instruction': 'Open PlayStation App or use your console',
        'is_active': True,
    },
    'xbox': {
        'name': 'Xbox',
        'slug': 'xbox',
        'icon': 'xbox',
        'color': '#107C10',
        'category': 'gaming',
        'file_limit': 'N/A',
        'file_limit_note': 'No file sharing feature',
        'users': '120 million',
        'share_method': 'message',
        'share_instruction': 'Send your SendFiles.Online link via Xbox messages to share game clips, screenshots, or files with your Xbox friends.',
        'app_instruction': 'Open Xbox App or use your console',
        'is_active': True,
    },
    'twitch': {
        'name': 'Twitch',
        'slug': 'twitch',
        'icon': 'twitch',
        'color': '#9146FF',
        'category': 'gaming',
        'file_limit': 'N/A',
        'file_limit_note': 'No file sharing in chat',
        'users': '140 million',
        'share_method': 'chat or whisper',
        'share_instruction': 'Share your SendFiles.Online link in Twitch chat or via whisper. Great for sharing stream overlays, assets, or files with your community.',
        'app_instruction': 'Open Twitch app or twitch.tv',
        'is_active': True,
    },

    # ==================== CLOUD STORAGE ====================
    'google-drive': {
        'name': 'Google Drive',
        'slug': 'google-drive',
        'icon': 'google-drive',
        'color': '#4285F4',
        'category': 'cloud',
        'file_limit': '5TB',
        'file_limit_note': '5TB per file, but sharing requires Google account',
        'users': '1 billion',
        'share_method': 'link sharing',
        'share_instruction': 'When Google Drive sharing permissions are too complex, use SendFiles.Online instead. Upload files, get a link, and share without requiring recipients to have Google accounts.',
        'app_instruction': 'Compare with drive.google.com',
        'is_active': True,
    },
    'dropbox': {
        'name': 'Dropbox',
        'slug': 'dropbox',
        'icon': 'dropbox',
        'color': '#0061FF',
        'category': 'cloud',
        'file_limit': '2GB',
        'file_limit_note': '2GB free storage total, 50GB with Plus',
        'users': '700 million',
        'share_method': 'link sharing',
        'share_instruction': 'SendFiles.Online is a simpler alternative to Dropbox for one-time transfers. No account required for recipients, and no storage limits to worry about.',
        'app_instruction': 'Compare with dropbox.com',
        'is_active': True,
    },
    'onedrive': {
        'name': 'OneDrive',
        'slug': 'onedrive',
        'icon': 'microsoft',
        'color': '#0078D4',
        'category': 'cloud',
        'file_limit': '250GB',
        'file_limit_note': '250GB per file with Office 365',
        'users': '250 million',
        'share_method': 'link sharing',
        'share_instruction': 'Skip OneDrive\'s complex sharing settings. Use SendFiles.Online to share large files with anyone - no Microsoft account required for your recipients.',
        'app_instruction': 'Compare with onedrive.com',
        'is_active': True,
    },
    'icloud': {
        'name': 'iCloud',
        'slug': 'icloud',
        'icon': 'apple',
        'color': '#3693F3',
        'category': 'cloud',
        'file_limit': '50GB',
        'file_limit_note': '50GB per file with iCloud Drive',
        'users': '850 million',
        'share_method': 'link sharing',
        'share_instruction': 'SendFiles.Online works on all devices, not just Apple. Share large files with anyone regardless of whether they use Apple products.',
        'app_instruction': 'Compare with icloud.com',
        'is_active': True,
    },

    # ==================== VIDEO & STREAMING ====================
    'youtube': {
        'name': 'YouTube',
        'slug': 'youtube',
        'icon': 'youtube',
        'color': '#FF0000',
        'category': 'social',
        'file_limit': '256GB',
        'file_limit_note': '256GB or 12 hours for verified accounts, 15 min otherwise',
        'users': '2.7 billion',
        'share_method': 'comment or community post',
        'share_instruction': 'Share your SendFiles.Online link in video comments, community posts, or video descriptions. Perfect for sharing project files, assets, or bonus content with your audience.',
        'app_instruction': 'Open YouTube and navigate to your video or community tab',
        'is_active': True,
    },
    'vimeo': {
        'name': 'Vimeo',
        'slug': 'vimeo',
        'icon': 'vimeo-v',
        'color': '#1AB7EA',
        'category': 'social',
        'file_limit': '500MB',
        'file_limit_note': '500MB/week on free plan, varies by subscription',
        'users': '260 million',
        'share_method': 'video description',
        'share_instruction': 'Add your SendFiles.Online link to video descriptions or comments. Great for sharing source files, behind-the-scenes content, or project assets with viewers.',
        'app_instruction': 'Open Vimeo and edit your video or post a comment',
        'is_active': True,
    },
    'dailymotion': {
        'name': 'Dailymotion',
        'slug': 'dailymotion',
        'icon': 'dailymotion',
        'color': '#0066DC',
        'category': 'social',
        'file_limit': '2GB',
        'file_limit_note': '2GB and 60 minutes per video',
        'users': '300 million',
        'share_method': 'video description',
        'share_instruction': 'Include your SendFiles.Online link in video descriptions or comments to share additional files with your audience.',
        'app_instruction': 'Open Dailymotion and navigate to your video',
        'is_active': True,
    },
    'rumble': {
        'name': 'Rumble',
        'slug': 'rumble',
        'icon': 'r',
        'color': '#85C742',
        'category': 'social',
        'file_limit': '15GB',
        'file_limit_note': '15GB per video',
        'users': '80 million',
        'share_method': 'video description',
        'share_instruction': 'Add your SendFiles.Online link to video descriptions or comments on Rumble to share supplementary files.',
        'app_instruction': 'Open Rumble and navigate to your video settings',
        'is_active': True,
    },

    # ==================== CREATIVE & ART PLATFORMS ====================
    'deviantart': {
        'name': 'DeviantArt',
        'slug': 'deviantart',
        'icon': 'deviantart',
        'color': '#05CC47',
        'category': 'social',
        'file_limit': '200MB',
        'file_limit_note': '200MB for images, 300MB for videos',
        'users': '61 million',
        'share_method': 'deviation description or comment',
        'share_instruction': 'Add your SendFiles.Online link to deviation descriptions, journals, or comments. Perfect for sharing high-resolution artwork, PSD files, or resource packs.',
        'app_instruction': 'Open DeviantArt and edit your submission',
        'is_active': True,
    },
    'artstation': {
        'name': 'ArtStation',
        'slug': 'artstation',
        'icon': 'artstation',
        'color': '#13AFF0',
        'category': 'social',
        'file_limit': '200MB',
        'file_limit_note': '200MB per file',
        'users': '20 million',
        'share_method': 'project description',
        'share_instruction': 'Include your SendFiles.Online link in project descriptions to share source files, 3D models, or high-resolution renders with other artists.',
        'app_instruction': 'Open ArtStation and edit your project',
        'is_active': True,
    },
    'behance': {
        'name': 'Behance',
        'slug': 'behance',
        'icon': 'behance',
        'color': '#1769FF',
        'category': 'social',
        'file_limit': '25MB',
        'file_limit_note': '25MB per image, 1GB for video',
        'users': '40 million',
        'share_method': 'project description',
        'share_instruction': 'Add your SendFiles.Online link to project descriptions to share design source files, mockups, or additional assets with viewers.',
        'app_instruction': 'Open Behance and edit your project',
        'is_active': True,
    },
    'dribbble': {
        'name': 'Dribbble',
        'slug': 'dribbble',
        'icon': 'dribbble',
        'color': '#EA4C89',
        'category': 'social',
        'file_limit': '50MB',
        'file_limit_note': '50MB for videos',
        'users': '10 million',
        'share_method': 'shot description',
        'share_instruction': 'Include your SendFiles.Online link in shot descriptions to share design files, templates, or full project assets with the design community.',
        'app_instruction': 'Open Dribbble and edit your shot',
        'is_active': True,
    },
    'pixiv': {
        'name': 'Pixiv',
        'slug': 'pixiv',
        'icon': 'p',
        'color': '#0096FA',
        'category': 'social',
        'file_limit': '32MB',
        'file_limit_note': '32MB per image',
        'users': '84 million',
        'share_method': 'caption or fanbox',
        'share_instruction': 'Add your SendFiles.Online link to illustration captions or Fanbox posts to share high-resolution artwork or resource files.',
        'app_instruction': 'Open Pixiv and edit your illustration',
        'is_active': True,
    },

    # ==================== MUSIC PLATFORMS ====================
    'soundcloud': {
        'name': 'SoundCloud',
        'slug': 'soundcloud',
        'icon': 'soundcloud',
        'color': '#FF5500',
        'category': 'social',
        'file_limit': '500MB',
        'file_limit_note': '500MB and 5GB total on free plan',
        'users': '175 million',
        'share_method': 'track description or comment',
        'share_instruction': 'Add your SendFiles.Online link to track descriptions or comments to share stems, project files, or additional audio content.',
        'app_instruction': 'Open SoundCloud and edit your track',
        'is_active': True,
    },
    'bandcamp': {
        'name': 'Bandcamp',
        'slug': 'bandcamp',
        'icon': 'bandcamp',
        'color': '#629AA9',
        'category': 'social',
        'file_limit': '291MB',
        'file_limit_note': '291MB per track (FLAC/WAV)',
        'users': '7 million',
        'share_method': 'album description',
        'share_instruction': 'Include your SendFiles.Online link in album or track descriptions to share bonus content, stems, or supplementary files with your fans.',
        'app_instruction': 'Open Bandcamp and edit your release',
        'is_active': True,
    },
    'spotify': {
        'name': 'Spotify',
        'slug': 'spotify',
        'icon': 'spotify',
        'color': '#1DB954',
        'category': 'social',
        'file_limit': 'N/A',
        'file_limit_note': 'No file sharing feature',
        'users': '600 million',
        'share_method': 'bio link or social share',
        'share_instruction': 'Add your SendFiles.Online link to your artist bio or share it alongside Spotify links to give fans access to bonus content, stems, or exclusive files.',
        'app_instruction': 'Edit your Spotify for Artists profile or share via social media',
        'is_active': True,
    },

    # ==================== IMAGE HOSTING ====================
    'imgur': {
        'name': 'Imgur',
        'slug': 'imgur',
        'icon': 'images',
        'color': '#1BB76E',
        'category': 'social',
        'file_limit': '20MB',
        'file_limit_note': '20MB for images, 200MB for videos',
        'users': '300 million',
        'share_method': 'description or comment',
        'share_instruction': 'Add your SendFiles.Online link to image descriptions or comments to share original high-resolution files or related content.',
        'app_instruction': 'Open Imgur and edit your post',
        'is_active': True,
    },
    'flickr': {
        'name': 'Flickr',
        'slug': 'flickr',
        'icon': 'flickr',
        'color': '#0063DC',
        'category': 'social',
        'file_limit': '200MB',
        'file_limit_note': '200MB per photo',
        'users': '90 million',
        'share_method': 'photo description',
        'share_instruction': 'Include your SendFiles.Online link in photo descriptions to share RAW files, full-resolution versions, or related content.',
        'app_instruction': 'Open Flickr and edit your photo',
        'is_active': True,
    },
    'unsplash': {
        'name': 'Unsplash',
        'slug': 'unsplash',
        'icon': 'unsplash',
        'color': '#000000',
        'category': 'social',
        'file_limit': '30MB',
        'file_limit_note': '30MB recommended, larger files allowed',
        'users': '330 million',
        'share_method': 'profile link',
        'share_instruction': 'Share your SendFiles.Online link in your Unsplash profile to offer RAW files, presets, or other resources to people who download your photos.',
        'app_instruction': 'Edit your Unsplash profile',
        'is_active': True,
    },

    # ==================== CREATOR PLATFORMS ====================
    'patreon': {
        'name': 'Patreon',
        'slug': 'patreon',
        'icon': 'patreon',
        'color': '#FF424D',
        'category': 'professional',
        'file_limit': '200MB',
        'file_limit_note': '200MB per attachment',
        'users': '250 million',
        'share_method': 'post attachment or link',
        'share_instruction': 'Add your SendFiles.Online link to Patreon posts to share large files like 4K videos, PSD files, or resource packs that exceed Patreon\'s limits.',
        'app_instruction': 'Create a new Patreon post',
        'is_active': True,
    },
    'ko-fi': {
        'name': 'Ko-fi',
        'slug': 'ko-fi',
        'icon': 'coffee',
        'color': '#FF5E5B',
        'category': 'professional',
        'file_limit': '25MB',
        'file_limit_note': '25MB for gallery items',
        'users': '1 million',
        'share_method': 'post or shop link',
        'share_instruction': 'Include your SendFiles.Online link in Ko-fi posts or shop descriptions to deliver large files to supporters.',
        'app_instruction': 'Create a new Ko-fi post',
        'is_active': True,
    },
    'gumroad': {
        'name': 'Gumroad',
        'slug': 'gumroad',
        'icon': 'shopping-cart',
        'color': '#FF90E8',
        'category': 'professional',
        'file_limit': '16GB',
        'file_limit_note': '16GB per product, limited downloads',
        'users': '10 million',
        'share_method': 'product description',
        'share_instruction': 'Use SendFiles.Online links in product descriptions or delivery emails for an alternative file delivery method that doesn\'t count against your limits.',
        'app_instruction': 'Edit your Gumroad product',
        'is_active': True,
    },

    # ==================== REGIONAL PLATFORMS ====================
    'vk': {
        'name': 'VK (VKontakte)',
        'slug': 'vk',
        'icon': 'vk',
        'color': '#4680C2',
        'category': 'social',
        'file_limit': '200MB',
        'file_limit_note': '200MB for documents',
        'users': '100 million',
        'share_method': 'post or message',
        'share_instruction': 'Share your SendFiles.Online link in VK posts, messages, or group discussions. Great for sharing larger files with Russian-speaking audiences.',
        'app_instruction': 'Open VK and create a post or message',
        'is_active': True,
    },
    'bluesky': {
        'name': 'Bluesky',
        'slug': 'bluesky',
        'icon': 'cloud',
        'color': '#0085FF',
        'category': 'social',
        'file_limit': '1MB',
        'file_limit_note': '1MB for images',
        'users': '10 million',
        'share_method': 'post',
        'share_instruction': 'Post your SendFiles.Online link on Bluesky to share larger files with your followers. Perfect for sharing high-res images or documents.',
        'app_instruction': 'Open Bluesky and create a post',
        'is_active': True,
    },
    'mastodon': {
        'name': 'Mastodon',
        'slug': 'mastodon',
        'icon': 'mastodon',
        'color': '#6364FF',
        'category': 'social',
        'file_limit': '40MB',
        'file_limit_note': '40MB for media, varies by instance',
        'users': '10 million',
        'share_method': 'toot',
        'share_instruction': 'Share your SendFiles.Online link in a Mastodon post (toot) to share larger files across the fediverse.',
        'app_instruction': 'Open your Mastodon instance and create a post',
        'is_active': True,
    },

    # ==================== FORUM & COMMUNITY ====================
    'discourse': {
        'name': 'Discourse Forums',
        'slug': 'discourse',
        'icon': 'discourse',
        'color': '#000000',
        'category': 'professional',
        'file_limit': '4MB',
        'file_limit_note': '4MB default, varies by forum',
        'users': 'millions',
        'share_method': 'post',
        'share_instruction': 'Add your SendFiles.Online link to forum posts when you need to share files larger than the forum allows.',
        'app_instruction': 'Navigate to your Discourse forum',
        'is_active': True,
    },
    'quora': {
        'name': 'Quora',
        'slug': 'quora',
        'icon': 'quora',
        'color': '#B92B27',
        'category': 'social',
        'file_limit': 'N/A',
        'file_limit_note': 'Images only, no file uploads',
        'users': '400 million',
        'share_method': 'answer or post',
        'share_instruction': 'Include your SendFiles.Online link in Quora answers or posts to share supplementary files, documents, or resources.',
        'app_instruction': 'Open Quora and write an answer',
        'is_active': True,
    },

    # ==================== FILE HOSTING ====================
    'gofile': {
        'name': 'Gofile',
        'slug': 'gofile',
        'icon': 'cloud-upload-alt',
        'color': '#3b82f6',
        'category': 'cloud',
        'file_limit': 'Unlimited',
        'file_limit_note': 'No size limit, but files expire',
        'users': 'millions',
        'share_method': 'link sharing',
        'share_instruction': 'SendFiles.Online offers 14-day guaranteed storage vs Gofile\'s uncertain expiration. Upload once, share the reliable link anywhere.',
        'app_instruction': 'Compare with gofile.io',
        'is_active': True,
    },
    'wetransfer': {
        'name': 'WeTransfer',
        'slug': 'wetransfer',
        'icon': 'paper-plane',
        'color': '#409FFF',
        'category': 'cloud',
        'file_limit': '2GB',
        'file_limit_note': '2GB free, 200GB with Pro',
        'users': '80 million',
        'share_method': 'link sharing',
        'share_instruction': 'SendFiles.Online offers 10GB free transfers - 5x more than WeTransfer\'s 2GB limit. No email required, just upload and share.',
        'app_instruction': 'Compare with wetransfer.com',
        'is_active': True,
    },
    'mega': {
        'name': 'MEGA',
        'slug': 'mega',
        'icon': 'm',
        'color': '#D9272E',
        'category': 'cloud',
        'file_limit': '20GB',
        'file_limit_note': '20GB free storage total',
        'users': '300 million',
        'share_method': 'link sharing',
        'share_instruction': 'SendFiles.Online is simpler for one-time transfers - no account needed, no storage management. Just upload, share the link, done.',
        'app_instruction': 'Compare with mega.io',
        'is_active': True,
    },
    'mediafire': {
        'name': 'MediaFire',
        'slug': 'mediafire',
        'icon': 'fire',
        'color': '#4285F4',
        'category': 'cloud',
        'file_limit': '10GB',
        'file_limit_note': '10GB per file, 10GB storage free',
        'users': '50 million',
        'share_method': 'link sharing',
        'share_instruction': 'Skip the account creation and ads. SendFiles.Online lets you share large files instantly without signup.',
        'app_instruction': 'Compare with mediafire.com',
        'is_active': True,
    },
    'pixeldrain': {
        'name': 'Pixeldrain',
        'slug': 'pixeldrain',
        'icon': 'cloud',
        'color': '#5865F2',
        'category': 'cloud',
        'file_limit': '20GB',
        'file_limit_note': '20GB per file',
        'users': 'millions',
        'share_method': 'link sharing',
        'share_instruction': 'Both offer anonymous file sharing. SendFiles.Online provides 14-day storage and optional password protection.',
        'app_instruction': 'Compare with pixeldrain.com',
        'is_active': True,
    },
    'catbox': {
        'name': 'Catbox',
        'slug': 'catbox',
        'icon': 'cat',
        'color': '#8B5CF6',
        'category': 'cloud',
        'file_limit': '200MB',
        'file_limit_note': '200MB per file',
        'users': 'millions',
        'share_method': 'link sharing',
        'share_instruction': 'Need to share files larger than Catbox\'s 200MB limit? SendFiles.Online handles up to 10GB with the same easy link sharing.',
        'app_instruction': 'Compare with catbox.moe',
        'is_active': True,
    },
    'streamable': {
        'name': 'Streamable',
        'slug': 'streamable',
        'icon': 'play-circle',
        'color': '#0C88F0',
        'category': 'cloud',
        'file_limit': '250MB',
        'file_limit_note': '250MB and 10 min for free',
        'users': 'millions',
        'share_method': 'link sharing',
        'share_instruction': 'For videos larger than Streamable allows, use SendFiles.Online. Share videos up to 10GB with a simple download link.',
        'app_instruction': 'Compare with streamable.com',
        'is_active': True,
    },

    # ==================== CONTENT PLATFORMS ====================
    '9gag': {
        'name': '9GAG',
        'slug': '9gag',
        'icon': 'laugh',
        'color': '#000000',
        'category': 'social',
        'file_limit': '200MB',
        'file_limit_note': '200MB for videos',
        'users': '150 million',
        'share_method': 'comment or post',
        'share_instruction': 'Share your SendFiles.Online link in 9GAG comments or posts to share files with the community.',
        'app_instruction': 'Open 9GAG and create a post or comment',
        'is_active': True,
    },
    'bitchute': {
        'name': 'BitChute',
        'slug': 'bitchute',
        'icon': 'b',
        'color': '#EF4136',
        'category': 'social',
        'file_limit': '2GB',
        'file_limit_note': '2GB per video',
        'users': '30 million',
        'share_method': 'video description',
        'share_instruction': 'Add your SendFiles.Online link to video descriptions to share additional files with your viewers.',
        'app_instruction': 'Open BitChute and edit your video',
        'is_active': True,
    },
    'bilibili': {
        'name': 'Bilibili',
        'slug': 'bilibili',
        'icon': 'tv',
        'color': '#00A1D6',
        'category': 'social',
        'file_limit': '8GB',
        'file_limit_note': '8GB per video for regular users',
        'users': '300 million',
        'share_method': 'video description or comment',
        'share_instruction': 'Include your SendFiles.Online link in video descriptions or comments to share additional resources.',
        'app_instruction': 'Open Bilibili and navigate to your video',
        'is_active': True,
    },
    'odysee': {
        'name': 'Odysee',
        'slug': 'odysee',
        'icon': 'o',
        'color': '#F0574B',
        'category': 'social',
        'file_limit': '16GB',
        'file_limit_note': '16GB per video',
        'users': '35 million',
        'share_method': 'video description',
        'share_instruction': 'Add your SendFiles.Online link to video descriptions to share supplementary files with your audience.',
        'app_instruction': 'Open Odysee and edit your video',
        'is_active': True,
    },
    '500px': {
        'name': '500px',
        'slug': '500px',
        'icon': '500px',
        'color': '#0099E5',
        'category': 'social',
        'file_limit': '30MB',
        'file_limit_note': '30MB for photos',
        'users': '16 million',
        'share_method': 'photo description',
        'share_instruction': 'Include your SendFiles.Online link in photo descriptions to share RAW files or full-resolution versions with other photographers.',
        'app_instruction': 'Open 500px and edit your photo',
        'is_active': True,
    },
    'newgrounds': {
        'name': 'Newgrounds',
        'slug': 'newgrounds',
        'icon': 'n',
        'color': '#FFC600',
        'text_color': '#000000',
        'category': 'social',
        'file_limit': '250MB',
        'file_limit_note': '250MB for most content',
        'users': '5 million',
        'share_method': 'description or comment',
        'share_instruction': 'Add your SendFiles.Online link to submission descriptions or comments to share source files, assets, or bonus content.',
        'app_instruction': 'Open Newgrounds and edit your submission',
        'is_active': True,
    },
    'itch-io': {
        'name': 'itch.io',
        'slug': 'itch-io',
        'icon': 'gamepad',
        'color': '#FA5C5C',
        'category': 'professional',
        'file_limit': '1GB',
        'file_limit_note': '1GB per file on free accounts',
        'users': '8 million',
        'share_method': 'game page or devlog',
        'share_instruction': 'Include your SendFiles.Online link in game descriptions or devlogs to share additional builds, assets, or bonus content.',
        'app_instruction': 'Open itch.io and edit your game page',
        'is_active': True,
    },
    'medium': {
        'name': 'Medium',
        'slug': 'medium',
        'icon': 'medium',
        'color': '#000000',
        'category': 'social',
        'file_limit': '25MB',
        'file_limit_note': '25MB for images and GIFs',
        'users': '100 million',
        'share_method': 'article',
        'share_instruction': 'Include your SendFiles.Online link in Medium articles to share downloadable resources, PDFs, or other files with readers.',
        'app_instruction': 'Open Medium and write or edit an article',
        'is_active': True,
    },
    'substack': {
        'name': 'Substack',
        'slug': 'substack',
        'icon': 's',
        'color': '#FF6719',
        'category': 'social',
        'file_limit': '50MB',
        'file_limit_note': '50MB for attachments',
        'users': '35 million',
        'share_method': 'newsletter',
        'share_instruction': 'Add your SendFiles.Online link to newsletters to share downloadable resources, PDFs, or bonus content with subscribers.',
        'app_instruction': 'Open Substack and compose your newsletter',
        'is_active': True,
    },
    'wordpress': {
        'name': 'WordPress',
        'slug': 'wordpress',
        'icon': 'wordpress',
        'color': '#21759B',
        'category': 'social',
        'file_limit': '1GB',
        'file_limit_note': '1GB on premium plans, varies',
        'users': '400 million',
        'share_method': 'post or page',
        'share_instruction': 'Embed your SendFiles.Online link in blog posts or pages to let readers download files without hosting them on your server.',
        'app_instruction': 'Open your WordPress dashboard',
        'is_active': True,
    },
    'blogger': {
        'name': 'Blogger',
        'slug': 'blogger',
        'icon': 'blogger-b',
        'color': '#FF5722',
        'category': 'social',
        'file_limit': '1GB',
        'file_limit_note': '1GB for videos, limited images',
        'users': 'millions',
        'share_method': 'blog post',
        'share_instruction': 'Include your SendFiles.Online link in blog posts to share downloadable files with your readers.',
        'app_instruction': 'Open Blogger and create a post',
        'is_active': True,
    },
    'wix': {
        'name': 'Wix',
        'slug': 'wix',
        'icon': 'wix',
        'color': '#FAAD4D',
        'text_color': '#000000',
        'category': 'professional',
        'file_limit': '1GB',
        'file_limit_note': '1GB per file on business plans',
        'users': '200 million',
        'share_method': 'website page',
        'share_instruction': 'Add your SendFiles.Online link to your Wix website to offer file downloads without using your site storage.',
        'app_instruction': 'Open your Wix editor',
        'is_active': True,
    },
    'squarespace': {
        'name': 'Squarespace',
        'slug': 'squarespace',
        'icon': 'squarespace',
        'color': '#000000',
        'category': 'professional',
        'file_limit': '20MB',
        'file_limit_note': '20MB per file for downloads',
        'users': '3 million',
        'share_method': 'website page',
        'share_instruction': 'Embed your SendFiles.Online link on your Squarespace site to share files larger than the 20MB limit.',
        'app_instruction': 'Open your Squarespace editor',
        'is_active': True,
    },
    'shopify': {
        'name': 'Shopify',
        'slug': 'shopify',
        'icon': 'shopify',
        'color': '#96BF48',
        'category': 'professional',
        'file_limit': '20MB',
        'file_limit_note': '20MB for digital products',
        'users': '4 million',
        'share_method': 'product page or email',
        'share_instruction': 'Use SendFiles.Online links to deliver digital products larger than Shopify\'s 20MB limit to your customers.',
        'app_instruction': 'Open your Shopify admin',
        'is_active': True,
    },

    # ==================== GAMING & MODDING ====================
    'nexusmods': {
        'name': 'Nexus Mods',
        'slug': 'nexusmods',
        'icon': 'puzzle-piece',
        'color': '#D98F40',
        'category': 'gaming',
        'file_limit': '10GB',
        'file_limit_note': '10GB per mod file',
        'users': '35 million',
        'share_method': 'mod description',
        'share_instruction': 'Add your SendFiles.Online link to mod descriptions as an alternative download source or for bonus content.',
        'app_instruction': 'Open Nexus Mods and edit your mod page',
        'is_active': True,
    },
    'moddb': {
        'name': 'ModDB',
        'slug': 'moddb',
        'icon': 'database',
        'color': '#E24F36',
        'category': 'gaming',
        'file_limit': '5GB',
        'file_limit_note': '5GB per download',
        'users': '20 million',
        'share_method': 'mod description',
        'share_instruction': 'Include your SendFiles.Online link in mod descriptions as an additional download mirror.',
        'app_instruction': 'Open ModDB and edit your mod page',
        'is_active': True,
    },
    'curseforge': {
        'name': 'CurseForge',
        'slug': 'curseforge',
        'icon': 'fire-alt',
        'color': '#F16436',
        'category': 'gaming',
        'file_limit': '300MB',
        'file_limit_note': '300MB per mod file',
        'users': '50 million',
        'share_method': 'project description',
        'share_instruction': 'Add your SendFiles.Online link to project descriptions for alternative downloads or additional resources.',
        'app_instruction': 'Open CurseForge and edit your project',
        'is_active': True,
    },
    'epic-games': {
        'name': 'Epic Games',
        'slug': 'epic-games',
        'icon': 'gamepad',
        'color': '#2F2D2E',
        'category': 'gaming',
        'file_limit': 'N/A',
        'file_limit_note': 'No direct file sharing',
        'users': '230 million',
        'share_method': 'social features',
        'share_instruction': 'Share your SendFiles.Online link with Epic Games friends to exchange game saves, screenshots, or other files.',
        'app_instruction': 'Open Epic Games Launcher',
        'is_active': True,
    },

    # ==================== OTHER PLATFORMS ====================
    'sms': {
        'name': 'SMS / Text Message',
        'slug': 'sms',
        'icon': 'comment-sms',
        'color': '#34C759',
        'category': 'messaging',
        'file_limit': '300KB',
        'file_limit_note': '300KB for MMS, varies by carrier',
        'users': 'billions',
        'share_method': 'text message',
        'share_instruction': 'Send your SendFiles.Online link via regular text message (SMS). Works on any phone, no app required. Your recipient just taps the link to download.',
        'app_instruction': 'Open your default messaging app',
        'is_active': True,
    },
    'email': {
        'name': 'Email',
        'slug': 'email',
        'icon': 'envelope',
        'color': '#6B7280',
        'category': 'email',
        'file_limit': '25MB',
        'file_limit_note': 'Most providers limit to 20-25MB',
        'users': '4 billion',
        'share_method': 'email',
        'share_instruction': 'Include your SendFiles.Online link in any email. Works with all email providers and avoids attachment limits, bounced emails, and inbox clutter.',
        'app_instruction': 'Open your email client',
        'is_active': True,
    },

    # ==================== FORUMS & COMMUNITIES ====================
    '4chan': {
        'name': '4chan',
        'slug': '4chan',
        'icon': 'hashtag',
        'color': '#006600',
        'category': 'social',
        'file_limit': '4MB',
        'file_limit_note': '4MB for images, 4MB for webm',
        'users': '20 million',
        'share_method': 'post',
        'share_instruction': 'Post your SendFiles.Online link in a thread to share larger files with other anons.',
        'app_instruction': 'Open 4chan and navigate to a board',
        'is_active': True,
    },
    'kiwifarms': {
        'name': 'Kiwi Farms',
        'slug': 'kiwifarms',
        'icon': 'leaf',
        'color': '#4A7C59',
        'category': 'social',
        'file_limit': '10MB',
        'file_limit_note': '10MB attachment limit',
        'users': 'millions',
        'share_method': 'post',
        'share_instruction': 'Include your SendFiles.Online link in forum posts to share larger files.',
        'app_instruction': 'Navigate to the forum',
        'is_active': True,
    },
    'something-awful': {
        'name': 'Something Awful',
        'slug': 'something-awful',
        'icon': 'grin-squint',
        'color': '#FF6600',
        'category': 'social',
        'file_limit': '2MB',
        'file_limit_note': '2MB for attachments',
        'users': '200,000',
        'share_method': 'forum post',
        'share_instruction': 'Share your SendFiles.Online link in forum threads to bypass the small attachment limit.',
        'app_instruction': 'Navigate to Something Awful forums',
        'is_active': True,
    },
    'resetera': {
        'name': 'ResetEra',
        'slug': 'resetera',
        'icon': 'comments',
        'color': '#EE4035',
        'category': 'social',
        'file_limit': '5MB',
        'file_limit_note': '5MB for attachments',
        'users': '1 million',
        'share_method': 'forum post',
        'share_instruction': 'Include your SendFiles.Online link in forum posts to share gaming files and media.',
        'app_instruction': 'Navigate to ResetEra forums',
        'is_active': True,
    },
    'neogaf': {
        'name': 'NeoGAF',
        'slug': 'neogaf',
        'icon': 'comments',
        'color': '#2C3E50',
        'category': 'social',
        'file_limit': '5MB',
        'file_limit_note': '5MB for attachments',
        'users': '500,000',
        'share_method': 'forum post',
        'share_instruction': 'Add your SendFiles.Online link to forum posts when sharing large gaming files.',
        'app_instruction': 'Navigate to NeoGAF forums',
        'is_active': True,
    },
    'stackexchange': {
        'name': 'Stack Exchange',
        'slug': 'stackexchange',
        'icon': 'stack-exchange',
        'color': '#1E5397',
        'category': 'professional',
        'file_limit': '2MB',
        'file_limit_note': '2MB for images only',
        'users': '100 million',
        'share_method': 'question or answer',
        'share_instruction': 'Include your SendFiles.Online link in questions or answers to share code files, datasets, or resources.',
        'app_instruction': 'Open Stack Overflow or any Stack Exchange site',
        'is_active': True,
    },
    'hackernews': {
        'name': 'Hacker News',
        'slug': 'hackernews',
        'icon': 'y-combinator',
        'color': '#FF6600',
        'category': 'professional',
        'file_limit': 'N/A',
        'file_limit_note': 'Text only, no file uploads',
        'users': '10 million',
        'share_method': 'comment',
        'share_instruction': 'Share your SendFiles.Online link in comments to provide downloadable resources to the HN community.',
        'app_instruction': 'Open news.ycombinator.com',
        'is_active': True,
    },
    'producthunt': {
        'name': 'Product Hunt',
        'slug': 'producthunt',
        'icon': 'product-hunt',
        'color': '#DA552F',
        'category': 'professional',
        'file_limit': 'N/A',
        'file_limit_note': 'Links only',
        'users': '10 million',
        'share_method': 'comment or product page',
        'share_instruction': 'Include your SendFiles.Online link in product descriptions or comments to share demos, assets, or resources.',
        'app_instruction': 'Open Product Hunt',
        'is_active': True,
    },

    # ==================== ANIME & MANGA ====================
    'myanimelist': {
        'name': 'MyAnimeList',
        'slug': 'myanimelist',
        'icon': 'list',
        'color': '#2E51A2',
        'category': 'social',
        'file_limit': 'N/A',
        'file_limit_note': 'No file sharing',
        'users': '25 million',
        'share_method': 'forum post or profile',
        'share_instruction': 'Share your SendFiles.Online link in MAL forums or comments to share anime-related files.',
        'app_instruction': 'Open MyAnimeList',
        'is_active': True,
    },
    'anilist': {
        'name': 'AniList',
        'slug': 'anilist',
        'icon': 'list-alt',
        'color': '#02A9FF',
        'category': 'social',
        'file_limit': 'N/A',
        'file_limit_note': 'No file sharing',
        'users': '5 million',
        'share_method': 'activity or forum',
        'share_instruction': 'Include your SendFiles.Online link in activities or forum posts to share anime resources.',
        'app_instruction': 'Open AniList',
        'is_active': True,
    },
    'crunchyroll': {
        'name': 'Crunchyroll',
        'slug': 'crunchyroll',
        'icon': 'play',
        'color': '#F47521',
        'category': 'social',
        'file_limit': 'N/A',
        'file_limit_note': 'Comments only',
        'users': '120 million',
        'share_method': 'comment',
        'share_instruction': 'Share your SendFiles.Online link in episode comments to share related files with other fans.',
        'app_instruction': 'Open Crunchyroll',
        'is_active': True,
    },
    'funimation': {
        'name': 'Funimation',
        'slug': 'funimation',
        'icon': 'f',
        'color': '#5B0BB5',
        'category': 'social',
        'file_limit': 'N/A',
        'file_limit_note': 'Comments only',
        'users': '15 million',
        'share_method': 'comment',
        'share_instruction': 'Include your SendFiles.Online link in comments to share fan content or resources.',
        'app_instruction': 'Open Funimation',
        'is_active': True,
    },

    # ==================== LIVESTREAMING ====================
    'kick': {
        'name': 'Kick',
        'slug': 'kick',
        'icon': 'k',
        'color': '#53FC18',
        'text_color': '#000000',
        'category': 'gaming',
        'file_limit': 'N/A',
        'file_limit_note': 'No file uploads in chat',
        'users': '30 million',
        'share_method': 'chat or bio',
        'share_instruction': 'Share your SendFiles.Online link in Kick chat or your channel bio to give viewers access to files.',
        'app_instruction': 'Open Kick',
        'is_active': True,
    },
    'dlive': {
        'name': 'DLive',
        'slug': 'dlive',
        'icon': 'd',
        'color': '#FFD300',
        'text_color': '#000000',
        'category': 'gaming',
        'file_limit': 'N/A',
        'file_limit_note': 'No file sharing in chat',
        'users': '5 million',
        'share_method': 'chat',
        'share_instruction': 'Paste your SendFiles.Online link in DLive chat to share files with viewers.',
        'app_instruction': 'Open DLive',
        'is_active': True,
    },
    'trovo': {
        'name': 'Trovo',
        'slug': 'trovo',
        'icon': 't',
        'color': '#19D463',
        'category': 'gaming',
        'file_limit': 'N/A',
        'file_limit_note': 'No file sharing',
        'users': '20 million',
        'share_method': 'chat',
        'share_instruction': 'Share your SendFiles.Online link in Trovo chat during streams.',
        'app_instruction': 'Open Trovo',
        'is_active': True,
    },
    'caffeine': {
        'name': 'Caffeine',
        'slug': 'caffeine',
        'icon': 'coffee',
        'color': '#0000FF',
        'category': 'gaming',
        'file_limit': 'N/A',
        'file_limit_note': 'Chat only',
        'users': '5 million',
        'share_method': 'chat',
        'share_instruction': 'Share your SendFiles.Online link in Caffeine chat with your audience.',
        'app_instruction': 'Open Caffeine',
        'is_active': True,
    },

    # ==================== PODCAST & AUDIO ====================
    'anchor': {
        'name': 'Anchor (Spotify for Podcasters)',
        'slug': 'anchor',
        'icon': 'anchor',
        'color': '#1DB954',
        'category': 'social',
        'file_limit': '250MB',
        'file_limit_note': '250MB per episode',
        'users': 'millions',
        'share_method': 'episode description',
        'share_instruction': 'Add your SendFiles.Online link to episode descriptions to share bonus content, transcripts, or resources.',
        'app_instruction': 'Open Spotify for Podcasters dashboard',
        'is_active': True,
    },
    'podbean': {
        'name': 'Podbean',
        'slug': 'podbean',
        'icon': 'podcast',
        'color': '#8C4BC9',
        'category': 'social',
        'file_limit': '5 hours',
        'file_limit_note': '5 hours of audio on free plan',
        'users': '600,000',
        'share_method': 'episode description',
        'share_instruction': 'Include your SendFiles.Online link in episode notes to share supplementary files.',
        'app_instruction': 'Open Podbean dashboard',
        'is_active': True,
    },
    'buzzsprout': {
        'name': 'Buzzsprout',
        'slug': 'buzzsprout',
        'icon': 'broadcast-tower',
        'color': '#FFC837',
        'text_color': '#000000',
        'category': 'social',
        'file_limit': '250MB',
        'file_limit_note': '250MB per episode',
        'users': '100,000',
        'share_method': 'show notes',
        'share_instruction': 'Add your SendFiles.Online link to show notes to share downloads with listeners.',
        'app_instruction': 'Open Buzzsprout dashboard',
        'is_active': True,
    },
    'mixcloud': {
        'name': 'Mixcloud',
        'slug': 'mixcloud',
        'icon': 'mixcloud',
        'color': '#5000FF',
        'category': 'social',
        'file_limit': '1GB',
        'file_limit_note': '1GB per mix',
        'users': '20 million',
        'share_method': 'mix description',
        'share_instruction': 'Include your SendFiles.Online link in mix descriptions to share tracklists, stems, or bonus content.',
        'app_instruction': 'Open Mixcloud',
        'is_active': True,
    },
    'hearthis': {
        'name': 'Hearthis.at',
        'slug': 'hearthis',
        'icon': 'headphones',
        'color': '#FF4500',
        'category': 'social',
        'file_limit': '500MB',
        'file_limit_note': '500MB per track',
        'users': '2 million',
        'share_method': 'track description',
        'share_instruction': 'Add your SendFiles.Online link to track descriptions to share stems or project files.',
        'app_instruction': 'Open Hearthis.at',
        'is_active': True,
    },

    # ==================== DEVELOPER PLATFORMS ====================
    'gitlab': {
        'name': 'GitLab',
        'slug': 'gitlab',
        'icon': 'gitlab',
        'color': '#FC6D26',
        'category': 'professional',
        'file_limit': '100MB',
        'file_limit_note': '100MB for LFS',
        'users': '30 million',
        'share_method': 'issue or comment',
        'share_instruction': 'Include your SendFiles.Online link in GitLab issues or comments to share large files, test data, or binaries.',
        'app_instruction': 'Open GitLab',
        'is_active': True,
    },
    'bitbucket': {
        'name': 'Bitbucket',
        'slug': 'bitbucket',
        'icon': 'bitbucket',
        'color': '#0052CC',
        'category': 'professional',
        'file_limit': '10MB',
        'file_limit_note': '10MB for downloads',
        'users': '10 million',
        'share_method': 'issue or PR',
        'share_instruction': 'Add your SendFiles.Online link to issues or pull requests to share large binaries or test files.',
        'app_instruction': 'Open Bitbucket',
        'is_active': True,
    },
    'codepen': {
        'name': 'CodePen',
        'slug': 'codepen',
        'icon': 'codepen',
        'color': '#000000',
        'category': 'professional',
        'file_limit': '10MB',
        'file_limit_note': '10MB for assets on Pro',
        'users': '5 million',
        'share_method': 'pen description or comment',
        'share_instruction': 'Include your SendFiles.Online link in pen descriptions to share source files or assets.',
        'app_instruction': 'Open CodePen',
        'is_active': True,
    },
    'codesandbox': {
        'name': 'CodeSandbox',
        'slug': 'codesandbox',
        'icon': 'cube',
        'color': '#040404',
        'category': 'professional',
        'file_limit': '20MB',
        'file_limit_note': '20MB workspace limit on free',
        'users': '2 million',
        'share_method': 'sandbox description',
        'share_instruction': 'Add your SendFiles.Online link to sandbox descriptions to share additional assets or documentation.',
        'app_instruction': 'Open CodeSandbox',
        'is_active': True,
    },
    'replit': {
        'name': 'Replit',
        'slug': 'replit',
        'icon': 'terminal',
        'color': '#F26207',
        'category': 'professional',
        'file_limit': '1GB',
        'file_limit_note': '1GB storage on free',
        'users': '25 million',
        'share_method': 'repl description or comment',
        'share_instruction': 'Include your SendFiles.Online link in repl descriptions to share data files or resources.',
        'app_instruction': 'Open Replit',
        'is_active': True,
    },
    'kaggle': {
        'name': 'Kaggle',
        'slug': 'kaggle',
        'icon': 'kaggle',
        'color': '#20BEFF',
        'category': 'professional',
        'file_limit': '100GB',
        'file_limit_note': '100GB for datasets',
        'users': '15 million',
        'share_method': 'notebook or discussion',
        'share_instruction': 'Share your SendFiles.Online link in notebook markdown or discussions for supplementary data.',
        'app_instruction': 'Open Kaggle',
        'is_active': True,
    },

    # ==================== EDUCATION ====================
    'canvas': {
        'name': 'Canvas LMS',
        'slug': 'canvas',
        'icon': 'graduation-cap',
        'color': '#E03D31',
        'category': 'professional',
        'file_limit': '500MB',
        'file_limit_note': '500MB default, varies by institution',
        'users': '30 million',
        'share_method': 'discussion or assignment',
        'share_instruction': 'Add your SendFiles.Online link in discussions or assignment comments to share large course materials.',
        'app_instruction': 'Open Canvas LMS',
        'is_active': True,
    },
    'blackboard': {
        'name': 'Blackboard',
        'slug': 'blackboard',
        'icon': 'chalkboard',
        'color': '#000000',
        'category': 'professional',
        'file_limit': '250MB',
        'file_limit_note': '250MB typical limit',
        'users': '20 million',
        'share_method': 'discussion or content',
        'share_instruction': 'Include your SendFiles.Online link in course content to share large educational files.',
        'app_instruction': 'Open Blackboard',
        'is_active': True,
    },
    'moodle': {
        'name': 'Moodle',
        'slug': 'moodle',
        'icon': 'graduation-cap',
        'color': '#F98012',
        'category': 'professional',
        'file_limit': '50MB',
        'file_limit_note': '50MB default, varies',
        'users': '300 million',
        'share_method': 'forum or activity',
        'share_instruction': 'Add your SendFiles.Online link to forums or activities to share course materials.',
        'app_instruction': 'Open your Moodle instance',
        'is_active': True,
    },
    'coursera': {
        'name': 'Coursera',
        'slug': 'coursera',
        'icon': 'book-open',
        'color': '#0056D2',
        'category': 'professional',
        'file_limit': 'N/A',
        'file_limit_note': 'Discussions only',
        'users': '100 million',
        'share_method': 'discussion forum',
        'share_instruction': 'Share your SendFiles.Online link in course discussions to exchange resources with classmates.',
        'app_instruction': 'Open Coursera',
        'is_active': True,
    },
    'udemy': {
        'name': 'Udemy',
        'slug': 'udemy',
        'icon': 'u',
        'color': '#A435F0',
        'category': 'professional',
        'file_limit': '4GB',
        'file_limit_note': '4GB per video lecture',
        'users': '60 million',
        'share_method': 'Q&A or resources',
        'share_instruction': 'Include your SendFiles.Online link in Q&A sections or course resources.',
        'app_instruction': 'Open Udemy',
        'is_active': True,
    },
    'skillshare': {
        'name': 'Skillshare',
        'slug': 'skillshare',
        'icon': 's',
        'color': '#00FF84',
        'text_color': '#000000',
        'category': 'professional',
        'file_limit': 'N/A',
        'file_limit_note': 'Discussions only',
        'users': '12 million',
        'share_method': 'project or discussion',
        'share_instruction': 'Add your SendFiles.Online link to projects or discussions to share resources.',
        'app_instruction': 'Open Skillshare',
        'is_active': True,
    },

    # ==================== SOCIAL DATING ====================
    'okcupid': {
        'name': 'OkCupid',
        'slug': 'okcupid',
        'icon': 'heart',
        'color': '#3F8CFF',
        'category': 'dating',
        'file_limit': 'N/A',
        'file_limit_note': 'No file sharing',
        'users': '10 million',
        'share_method': 'message',
        'share_instruction': 'Send your SendFiles.Online link in OkCupid messages to safely share photos or files.',
        'app_instruction': 'Open OkCupid',
        'is_active': True,
    },
    'plenty-of-fish': {
        'name': 'Plenty of Fish',
        'slug': 'plenty-of-fish',
        'icon': 'fish',
        'color': '#11A8D9',
        'category': 'dating',
        'file_limit': 'N/A',
        'file_limit_note': 'No file sharing',
        'users': '100 million',
        'share_method': 'message',
        'share_instruction': 'Share your SendFiles.Online link in messages to exchange photos safely.',
        'app_instruction': 'Open Plenty of Fish',
        'is_active': True,
    },
    'match': {
        'name': 'Match.com',
        'slug': 'match',
        'icon': 'heart',
        'color': '#F34B78',
        'category': 'dating',
        'file_limit': 'N/A',
        'file_limit_note': 'No file sharing',
        'users': '25 million',
        'share_method': 'message',
        'share_instruction': 'Include your SendFiles.Online link in messages to share photos or other files.',
        'app_instruction': 'Open Match.com',
        'is_active': True,
    },
    'grindr': {
        'name': 'Grindr',
        'slug': 'grindr',
        'icon': 'g',
        'color': '#FFBB00',
        'text_color': '#000000',
        'category': 'dating',
        'file_limit': 'N/A',
        'file_limit_note': 'Images only',
        'users': '13 million',
        'share_method': 'chat',
        'share_instruction': 'Share your SendFiles.Online link in Grindr chat to exchange files.',
        'app_instruction': 'Open Grindr',
        'is_active': True,
    },
    'scruff': {
        'name': 'Scruff',
        'slug': 'scruff',
        'icon': 's',
        'color': '#FFDE00',
        'text_color': '#000000',
        'category': 'dating',
        'file_limit': 'N/A',
        'file_limit_note': 'Limited media sharing',
        'users': '15 million',
        'share_method': 'message',
        'share_instruction': 'Share your SendFiles.Online link in Scruff messages.',
        'app_instruction': 'Open Scruff',
        'is_active': True,
    },
    'feeld': {
        'name': 'Feeld',
        'slug': 'feeld',
        'icon': 'f',
        'color': '#000000',
        'category': 'dating',
        'file_limit': 'N/A',
        'file_limit_note': 'No file sharing',
        'users': '2 million',
        'share_method': 'message',
        'share_instruction': 'Send your SendFiles.Online link in Feeld chats to share files safely.',
        'app_instruction': 'Open Feeld',
        'is_active': True,
    },

    # ==================== EVENTS & MEETUPS ====================
    'meetup': {
        'name': 'Meetup',
        'slug': 'meetup',
        'icon': 'meetup',
        'color': '#F64060',
        'category': 'social',
        'file_limit': 'N/A',
        'file_limit_note': 'No file uploads',
        'users': '50 million',
        'share_method': 'event description or comment',
        'share_instruction': 'Include your SendFiles.Online link in event descriptions to share materials with attendees.',
        'app_instruction': 'Open Meetup',
        'is_active': True,
    },
    'eventbrite': {
        'name': 'Eventbrite',
        'slug': 'eventbrite',
        'icon': 'calendar-alt',
        'color': '#F05537',
        'category': 'professional',
        'file_limit': 'N/A',
        'file_limit_note': 'No file sharing',
        'users': '50 million',
        'share_method': 'event description',
        'share_instruction': 'Add your SendFiles.Online link to event descriptions to share downloadable resources.',
        'app_instruction': 'Open Eventbrite',
        'is_active': True,
    },
    'luma': {
        'name': 'Luma',
        'slug': 'luma',
        'icon': 'calendar',
        'color': '#8B5CF6',
        'category': 'professional',
        'file_limit': 'N/A',
        'file_limit_note': 'No file sharing',
        'users': 'millions',
        'share_method': 'event page',
        'share_instruction': 'Include your SendFiles.Online link on Luma event pages to share materials with attendees.',
        'app_instruction': 'Open lu.ma',
        'is_active': True,
    },

    # ==================== PRIVACY-FOCUSED ====================
    'session': {
        'name': 'Session',
        'slug': 'session',
        'icon': 'lock',
        'color': '#00F782',
        'category': 'messaging',
        'file_limit': '10MB',
        'file_limit_note': '10MB attachment limit',
        'users': '1 million',
        'share_method': 'message',
        'share_instruction': 'Send your SendFiles.Online link in Session chats to share larger files while maintaining privacy.',
        'app_instruction': 'Open Session app',
        'is_active': True,
    },
    'element': {
        'name': 'Element (Matrix)',
        'slug': 'element',
        'icon': 'comments',
        'color': '#0DBD8B',
        'category': 'messaging',
        'file_limit': '100MB',
        'file_limit_note': '100MB default, varies by server',
        'users': '10 million',
        'share_method': 'message',
        'share_instruction': 'Share your SendFiles.Online link in Element chats when you need to send files larger than the server limit.',
        'app_instruction': 'Open Element app',
        'is_active': True,
    },
    'briar': {
        'name': 'Briar',
        'slug': 'briar',
        'icon': 'shield-alt',
        'color': '#448553',
        'category': 'messaging',
        'file_limit': 'N/A',
        'file_limit_note': 'Text only, very limited media',
        'users': '100,000',
        'share_method': 'message',
        'share_instruction': 'Share your SendFiles.Online link in Briar to exchange files while maintaining security.',
        'app_instruction': 'Open Briar app',
        'is_active': True,
    },
    'keybase': {
        'name': 'Keybase',
        'slug': 'keybase',
        'icon': 'key',
        'color': '#33A0FF',
        'category': 'messaging',
        'file_limit': '250GB',
        'file_limit_note': '250GB total storage',
        'users': '500,000',
        'share_method': 'chat',
        'share_instruction': 'Share your SendFiles.Online link in Keybase chats when you need to share files with non-Keybase users.',
        'app_instruction': 'Open Keybase',
        'is_active': True,
    },
    'wire': {
        'name': 'Wire',
        'slug': 'wire',
        'icon': 'comments',
        'color': '#000000',
        'category': 'messaging',
        'file_limit': '25MB',
        'file_limit_note': '25MB attachment limit',
        'users': '500,000',
        'share_method': 'message',
        'share_instruction': 'Send your SendFiles.Online link in Wire conversations to share files larger than 25MB.',
        'app_instruction': 'Open Wire app',
        'is_active': True,
    },
    'wickr': {
        'name': 'Wickr',
        'slug': 'wickr',
        'icon': 'comment-dots',
        'color': '#FF6633',
        'category': 'messaging',
        'file_limit': '25MB',
        'file_limit_note': '25MB for most plans',
        'users': '5 million',
        'share_method': 'message',
        'share_instruction': 'Share your SendFiles.Online link in Wickr messages to send larger files securely.',
        'app_instruction': 'Open Wickr app',
        'is_active': True,
    },

    # ==================== DESIGN TOOLS ====================
    'figma': {
        'name': 'Figma',
        'slug': 'figma',
        'icon': 'figma',
        'color': '#F24E1E',
        'category': 'professional',
        'file_limit': 'Unlimited',
        'file_limit_note': 'But slow with large files',
        'users': '4 million',
        'share_method': 'comment or description',
        'share_instruction': 'Add your SendFiles.Online link in Figma comments or file descriptions to share assets, fonts, or source files.',
        'app_instruction': 'Open Figma',
        'is_active': True,
    },
    'sketch': {
        'name': 'Sketch',
        'slug': 'sketch',
        'icon': 'sketch',
        'color': '#FDAD00',
        'text_color': '#000000',
        'category': 'professional',
        'file_limit': 'N/A',
        'file_limit_note': 'Cloud sharing only',
        'users': '1 million',
        'share_method': 'document link',
        'share_instruction': 'Share your SendFiles.Online link alongside Sketch files to provide source assets or additional resources.',
        'app_instruction': 'Open Sketch',
        'is_active': True,
    },
    'invision': {
        'name': 'InVision',
        'slug': 'invision',
        'icon': 'invision',
        'color': '#FF3366',
        'category': 'professional',
        'file_limit': '50MB',
        'file_limit_note': '50MB per asset',
        'users': '7 million',
        'share_method': 'comment',
        'share_instruction': 'Include your SendFiles.Online link in InVision comments to share large design assets.',
        'app_instruction': 'Open InVision',
        'is_active': True,
    },
    'canva': {
        'name': 'Canva',
        'slug': 'canva',
        'icon': 'palette',
        'color': '#00C4CC',
        'category': 'professional',
        'file_limit': '25MB',
        'file_limit_note': '25MB for uploads on free plan',
        'users': '150 million',
        'share_method': 'design link',
        'share_instruction': 'Share your SendFiles.Online link to provide original source files or high-resolution exports.',
        'app_instruction': 'Open Canva',
        'is_active': True,
    },
    'adobe-creative-cloud': {
        'name': 'Adobe Creative Cloud',
        'slug': 'adobe-creative-cloud',
        'icon': 'adobe',
        'color': '#FF0000',
        'category': 'professional',
        'file_limit': '100GB',
        'file_limit_note': '100GB cloud storage',
        'users': '30 million',
        'share_method': 'shared link',
        'share_instruction': 'Use SendFiles.Online when sharing with non-Adobe users or when you need simpler sharing without Creative Cloud.',
        'app_instruction': 'Open Adobe Creative Cloud',
        'is_active': True,
    },

    # ==================== VR & 3D ====================
    'sketchfab': {
        'name': 'Sketchfab',
        'slug': 'sketchfab',
        'icon': 'cube',
        'color': '#1CAAD9',
        'category': 'social',
        'file_limit': '200MB',
        'file_limit_note': '200MB on free plan',
        'users': '5 million',
        'share_method': 'model description',
        'share_instruction': 'Include your SendFiles.Online link in model descriptions to share source files, textures, or original 3D files.',
        'app_instruction': 'Open Sketchfab',
        'is_active': True,
    },
    'cgtrader': {
        'name': 'CGTrader',
        'slug': 'cgtrader',
        'icon': 'cube',
        'color': '#F3723C',
        'category': 'professional',
        'file_limit': '500MB',
        'file_limit_note': '500MB per file',
        'users': '6 million',
        'share_method': 'model description',
        'share_instruction': 'Add your SendFiles.Online link in model descriptions as an alternative download source.',
        'app_instruction': 'Open CGTrader',
        'is_active': True,
    },
    'turbosquid': {
        'name': 'TurboSquid',
        'slug': 'turbosquid',
        'icon': 'cube',
        'color': '#E94C2B',
        'category': 'professional',
        'file_limit': '500MB',
        'file_limit_note': '500MB typical',
        'users': '4 million',
        'share_method': 'product description',
        'share_instruction': 'Include your SendFiles.Online link for alternative file delivery or bonus content.',
        'app_instruction': 'Open TurboSquid',
        'is_active': True,
    },
    'vrchat': {
        'name': 'VRChat',
        'slug': 'vrchat',
        'icon': 'vr-cardboard',
        'color': '#095D6A',
        'category': 'gaming',
        'file_limit': 'N/A',
        'file_limit_note': 'No direct file sharing',
        'users': '30 million',
        'share_method': 'bio or external links',
        'share_instruction': 'Share your SendFiles.Online link on VRChat social features or Discord to distribute avatar files and world assets.',
        'app_instruction': 'Open VRChat',
        'is_active': True,
    },

    # ==================== WRITING & PUBLISHING ====================
    'wattpad': {
        'name': 'Wattpad',
        'slug': 'wattpad',
        'icon': 'book',
        'color': '#FF500A',
        'category': 'social',
        'file_limit': 'N/A',
        'file_limit_note': 'Text only',
        'users': '90 million',
        'share_method': 'story description or comment',
        'share_instruction': 'Add your SendFiles.Online link to story descriptions to share bonus content, artwork, or supplementary files.',
        'app_instruction': 'Open Wattpad',
        'is_active': True,
    },
    'royal-road': {
        'name': 'Royal Road',
        'slug': 'royal-road',
        'icon': 'crown',
        'color': '#003366',
        'category': 'social',
        'file_limit': 'N/A',
        'file_limit_note': 'Text only',
        'users': '5 million',
        'share_method': 'author note or comment',
        'share_instruction': 'Include your SendFiles.Online link in author notes to share character art, maps, or bonus content.',
        'app_instruction': 'Open Royal Road',
        'is_active': True,
    },
    'scribblehub': {
        'name': 'ScribbleHub',
        'slug': 'scribblehub',
        'icon': 'pen-nib',
        'color': '#2B2D42',
        'category': 'social',
        'file_limit': 'N/A',
        'file_limit_note': 'Text only',
        'users': '1 million',
        'share_method': 'author note',
        'share_instruction': 'Add your SendFiles.Online link in author notes for bonus content.',
        'app_instruction': 'Open ScribbleHub',
        'is_active': True,
    },
    'ao3': {
        'name': 'Archive of Our Own',
        'slug': 'ao3',
        'icon': 'archive',
        'color': '#990000',
        'category': 'social',
        'file_limit': 'N/A',
        'file_limit_note': 'Text only, no file uploads',
        'users': '10 million',
        'share_method': 'author note',
        'share_instruction': 'Include your SendFiles.Online link in author notes to share artwork, podfic files, or other fan content.',
        'app_instruction': 'Open AO3',
        'is_active': True,
    },
    'fanfiction-net': {
        'name': 'FanFiction.Net',
        'slug': 'fanfiction-net',
        'icon': 'pen-fancy',
        'color': '#5C94CE',
        'category': 'social',
        'file_limit': 'N/A',
        'file_limit_note': 'Text only',
        'users': '15 million',
        'share_method': 'author note',
        'share_instruction': 'Add your SendFiles.Online link in author notes to share fan art or other content.',
        'app_instruction': 'Open FanFiction.Net',
        'is_active': True,
    },
}


def get_platform(slug):
    """Get a single platform by slug."""
    return PLATFORMS.get(slug)


def get_all_platforms():
    """Get all active platforms."""
    return {k: v for k, v in PLATFORMS.items() if v.get('is_active', True)}


def get_platforms_by_category():
    """Get platforms organized by category."""
    platforms_by_cat = {}
    for slug, platform in PLATFORMS.items():
        if not platform.get('is_active', True):
            continue
        category = platform.get('category', 'other')
        if category not in platforms_by_cat:
            platforms_by_cat[category] = []
        platforms_by_cat[category].append({**platform, 'slug': slug})

    # Sort by category order
    sorted_cats = sorted(
        platforms_by_cat.items(),
        key=lambda x: PLATFORM_CATEGORIES.get(x[0], {}).get('order', 99)
    )
    return dict(sorted_cats)


def get_related_platforms(current_slug, limit=6):
    """Get related platforms (same category, then others)."""
    current = PLATFORMS.get(current_slug)
    if not current:
        return []

    current_cat = current.get('category')
    related = []

    # First, add platforms from same category
    for slug, platform in PLATFORMS.items():
        if slug != current_slug and platform.get('category') == current_cat and platform.get('is_active', True):
            related.append({**platform, 'slug': slug})

    # Then add from other categories
    for slug, platform in PLATFORMS.items():
        if slug != current_slug and platform.get('category') != current_cat and platform.get('is_active', True):
            related.append({**platform, 'slug': slug})

    return related[:limit]


def generate_faqs(platform):
    """Generate FAQs for a platform."""
    name = platform['name']
    limit = platform['file_limit']

    return [
        {
            'question': f'How do I send large files on {name}?',
            'answer': f'Upload your files to SendFiles.Online (up to 10GB free), copy the download link, and share it on {name}. Your recipient can download directly without any account.'
        },
        {
            'question': f'What is the file size limit on {name}?',
            'answer': f'{name} has a file size limit of {limit}. SendFiles.Online lets you bypass this limitation by sharing a download link instead of the actual file.'
        },
        {
            'question': f'Can I send files larger than {limit} on {name}?',
            'answer': f'Yes! While {name} limits direct file sharing to {limit}, you can use SendFiles.Online to share files up to 10GB. Just upload your files, get a link, and share it on {name}.'
        },
        {
            'question': f'Is it free to send large files on {name}?',
            'answer': f'Yes, SendFiles.Online offers free transfers up to 10GB with 14-day storage. Upload your files, share the link on {name}, and your recipients can download for free.'
        },
        {
            'question': 'How long do shared files stay available?',
            'answer': 'Free transfers on SendFiles.Online are available for 14 days. Your recipients can download the files as many times as needed during this period.'
        },
        {
            'question': f'Can I password protect files I share on {name}?',
            'answer': 'Yes! When uploading to SendFiles.Online, you can add password protection. Only recipients with the password can download the files.'
        },
        {
            'question': 'Do recipients need to create an account?',
            'answer': 'No. Recipients just click your SendFiles.Online link and download directly. No signup, no account, no app installation required.'
        },
    ]
