# Generated by Django 5.2.10 on 2026-02-01 05:31

import django.db.models.deletion
import transfers.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_id', models.CharField(default=transfers.models.generate_short_id, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sender_ip', models.GenericIPAddressField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('password_hash', models.CharField(blank=True, max_length=128)),
                ('encryption_type', models.CharField(choices=[('none', 'No Encryption'), ('server', 'Server-Side Encryption'), ('client', 'Client-Side E2E')], default='none', max_length=20)),
                ('max_downloads', models.PositiveIntegerField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('recipient_emails', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('ready', 'Ready'), ('expired', 'Expired'), ('deleted', 'Deleted')], default='uploading', max_length=20)),
                ('total_size', models.BigIntegerField(default=0)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=512)),
                ('stored_name', models.CharField(max_length=128)),
                ('size', models.BigIntegerField()),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=255)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload_complete', models.BooleanField(default=False)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='transfers.transfer')),
            ],
            options={
                'ordering': ['original_name'],
            },
        ),
        migrations.CreateModel(
            name='DownloadEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('is_full_download', models.BooleanField(default=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_events', to='transfers.transfer')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='download_events', to='transfers.transferfile')),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['short_id'], name='transfers_t_short_i_b4d88d_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['status', 'expires_at'], name='transfers_t_status_8e1ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['sender_ip', 'created_at'], name='transfers_t_sender__309e71_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadevent',
            index=models.Index(fields=['transfer', 'downloaded_at'], name='transfers_d_transfe_c4e9b5_idx'),
        ),
    ]
