# Generated by Django 5.2.10 on 2026-02-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferfile',
            name='preview_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transferfile',
            name='preview_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('pdf', 'PDF'), ('text', 'Text/Code'), ('office', 'Office Document'), ('none', 'No Preview')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='transferfile',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
