# Generated by Django 5.2.10 on 2026-02-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_add_preview_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='notify_on_download',
            field=models.BooleanField(default=False),
        ),
    ]
