# Generated by Django 5.2.10 on 2026-02-05 22:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0004_add_monthly_usage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPortal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('welcome_message', models.TextField(blank=True, help_text='Message shown to uploaders')),
                ('logo', models.CharField(blank=True, max_length=512)),
                ('primary_color', models.CharField(default='#111111', max_length=7)),
                ('background_image', models.CharField(blank=True, max_length=512)),
                ('max_file_size', models.BigIntegerField(default=3221225472)),
                ('max_files', models.PositiveIntegerField(default=50)),
                ('allowed_extensions', models.TextField(blank=True, help_text="Comma-separated, e.g., 'pdf,doc,docx'")),
                ('require_email', models.BooleanField(default=True)),
                ('require_name', models.BooleanField(default=False)),
                ('custom_fields', models.JSONField(blank=True, default=list)),
                ('notify_on_upload', models.BooleanField(default=True)),
                ('notification_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_uploads', models.PositiveIntegerField(default=0)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploader_name', models.CharField(blank=True, max_length=255)),
                ('uploader_email', models.EmailField(blank=True, max_length=254)),
                ('uploader_ip', models.GenericIPAddressField()),
                ('message', models.TextField(blank=True)),
                ('custom_responses', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_upload', to='transfers.transfer')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='transfers.uploadportal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
