# Generated by Django 5.2.10 on 2026-02-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0005_add_upload_portals'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='allowed_domains',
            field=models.TextField(blank=True, help_text='Comma-separated list of allowed email domains'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='allowed_ips',
            field=models.TextField(blank=True, help_text='Comma-separated list of allowed IP addresses/ranges'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='require_email_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfer',
            name='two_factor_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='transfer',
            name='virus_scan_result',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='virus_scan_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('infected', 'Infected'), ('error', 'Scan Error')], default='pending', max_length=20),
        ),
    ]
