# Generated by Django 5.2.10 on 2026-02-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('en_label', models.CharField(max_length=250)),
                ('iso', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=250, unique=True)),
                ('text', models.TextField()),
                ('translated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=250)),
                ('language', models.CharField(max_length=10)),
                ('text', models.TextField()),
            ],
            options={
                'unique_together': {('language', 'code_name')},
            },
        ),
    ]
