# Generated by Django 5.2.10 on 2026-02-01 05:29

import app.utils
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=250, unique=True)),
                ('price', models.IntegerField(default=1)),
                ('label_price', models.IntegerField(blank=True, null=True)),
                ('credits', models.IntegerField(default=0)),
                ('paypal_product_key', models.CharField(blank=True, max_length=250, null=True)),
                ('paypal_key', models.CharField(blank=True, max_length=250, null=True)),
                ('coinbase_key', models.CharField(blank=True, max_length=250, null=True)),
                ('stripe_key', models.CharField(blank=True, max_length=250, null=True)),
                ('square_key', models.CharField(blank=True, max_length=250, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('yearly_subscription', models.BooleanField(default=False)),
                ('is_subscription', models.BooleanField(default=False)),
                ('is_api_plan', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(max_length=20, null=True)),
                ('amount', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('failed', 'failed'), ('success', 'success'), ('pending', 'pending'), ('refunded', 'refunded')], default='pending', max_length=100)),
                ('payment_token', models.CharField(max_length=250, null=True)),
                ('refund_token', models.CharField(max_length=250, null=True)),
                ('customer_token', models.CharField(max_length=250, null=True)),
                ('card_token', models.CharField(max_length=250, null=True)),
                ('comments', models.TextField(null=True)),
                ('payment_data', models.TextField(null=True)),
                ('used_card_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('used_card_exp_month', models.CharField(blank=True, max_length=50, null=True)),
                ('used_card_exp_year', models.CharField(blank=True, max_length=50, null=True)),
                ('used_card_last_digits', models.CharField(blank=True, max_length=50, null=True)),
                ('uuid', models.CharField(default=app.utils.Utils.generate_hex_uuid, max_length=250)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
